/*

 BOARD.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 5
   Map size      : 20 x 18
   Tile set      : Shogitiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Board_h_INCLUDE
#define __Board_h_INCLUDE

#define BattlefieldWidth 20
#define BattlefieldHeight 18
#define BattlefieldBank 5

#define Battlefield BattlefieldPLN0
extern const unsigned char BattlefieldPLN0[];

#endif

/* End of BOARD.H */
