/*

 CURSOR.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 2

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __cursor_h_INCLUDE
#define __cursor_h_INCLUDE

/* Bank of tiles. */
#define arrowcursorBank 3

/* Super Gameboy palette 0 */
#define arrowcursorSGBPal0c0 32767
#define arrowcursorSGBPal0c1 31
#define arrowcursorSGBPal0c2 24
#define arrowcursorSGBPal0c3 12

/* Super Gameboy palette 1 */
#define arrowcursorSGBPal1c0 32767
#define arrowcursorSGBPal1c1 25568
#define arrowcursorSGBPal1c2 17152
#define arrowcursorSGBPal1c3 8576

/* Super Gameboy palette 2 */
#define arrowcursorSGBPal2c0 32767
#define arrowcursorSGBPal2c1 8935
#define arrowcursorSGBPal2c2 6596
#define arrowcursorSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define arrowcursorSGBPal3c0 32767
#define arrowcursorSGBPal3c1 8935
#define arrowcursorSGBPal3c2 6596
#define arrowcursorSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define arrowcursorCGBPal0c0 6076
#define arrowcursorCGBPal0c1 8935
#define arrowcursorCGBPal0c2 6596
#define arrowcursorCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define arrowcursorCGBPal1c0 6076
#define arrowcursorCGBPal1c1 8935
#define arrowcursorCGBPal1c2 6596
#define arrowcursorCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define arrowcursorCGBPal2c0 6076
#define arrowcursorCGBPal2c1 8935
#define arrowcursorCGBPal2c2 6596
#define arrowcursorCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define arrowcursorCGBPal3c0 6076
#define arrowcursorCGBPal3c1 8935
#define arrowcursorCGBPal3c2 6596
#define arrowcursorCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define arrowcursorCGBPal4c0 6076
#define arrowcursorCGBPal4c1 8935
#define arrowcursorCGBPal4c2 6596
#define arrowcursorCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define arrowcursorCGBPal5c0 6076
#define arrowcursorCGBPal5c1 8935
#define arrowcursorCGBPal5c2 6596
#define arrowcursorCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define arrowcursorCGBPal6c0 6076
#define arrowcursorCGBPal6c1 8935
#define arrowcursorCGBPal6c2 6596
#define arrowcursorCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define arrowcursorCGBPal7c0 6076
#define arrowcursorCGBPal7c1 8935
#define arrowcursorCGBPal7c2 6596
#define arrowcursorCGBPal7c3 5344

/* SGB palette entries. */
#define arrowcursorSGB0 0
#define arrowcursorSGB1 1
#define arrowcursorSGB2 1
/* Start of tile array. */
extern const void __bank_arrowcursor;
extern const unsigned char arrowcursor[];

#endif

/* End of CURSOR.H */
