/*

 CUTSCENETILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 165

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __cutscenetiles_h_INCLUDE
#define __cutscenetiles_h_INCLUDE

/* Bank of tiles. */
#define fujitilesBank 0

/* Super Gameboy palette 0 */
#define fujitilesSGBPal0c0 32767
#define fujitilesSGBPal0c1 32656
#define fujitilesSGBPal0c2 32128
#define fujitilesSGBPal0c3 0

/* Super Gameboy palette 1 */
#define fujitilesSGBPal1c0 32767
#define fujitilesSGBPal1c1 17311
#define fujitilesSGBPal1c2 8728
#define fujitilesSGBPal1c3 0

/* Super Gameboy palette 2 */
#define fujitilesSGBPal2c0 32767
#define fujitilesSGBPal2c1 31
#define fujitilesSGBPal2c2 6596
#define fujitilesSGBPal2c3 0

/* Super Gameboy palette 3 */
#define fujitilesSGBPal3c0 32767
#define fujitilesSGBPal3c1 8935
#define fujitilesSGBPal3c2 6596
#define fujitilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define fujitilesCGBPal0c0 6076
#define fujitilesCGBPal0c1 8935
#define fujitilesCGBPal0c2 6596
#define fujitilesCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define fujitilesCGBPal1c0 6076
#define fujitilesCGBPal1c1 8935
#define fujitilesCGBPal1c2 6596
#define fujitilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define fujitilesCGBPal2c0 6076
#define fujitilesCGBPal2c1 8935
#define fujitilesCGBPal2c2 6596
#define fujitilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define fujitilesCGBPal3c0 6076
#define fujitilesCGBPal3c1 8935
#define fujitilesCGBPal3c2 6596
#define fujitilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define fujitilesCGBPal4c0 6076
#define fujitilesCGBPal4c1 8935
#define fujitilesCGBPal4c2 6596
#define fujitilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define fujitilesCGBPal5c0 6076
#define fujitilesCGBPal5c1 8935
#define fujitilesCGBPal5c2 6596
#define fujitilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define fujitilesCGBPal6c0 6076
#define fujitilesCGBPal6c1 8935
#define fujitilesCGBPal6c2 6596
#define fujitilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define fujitilesCGBPal7c0 6076
#define fujitilesCGBPal7c1 8935
#define fujitilesCGBPal7c2 6596
#define fujitilesCGBPal7c3 5344

/* SGB palette entries. */
#define fujitilesSGB0 0
#define fujitilesSGB1 2
#define fujitilesSGB2 2
#define fujitilesSGB3 2
#define fujitilesSGB4 2
#define fujitilesSGB5 1
#define fujitilesSGB6 1
#define fujitilesSGB7 0
#define fujitilesSGB8 0
#define fujitilesSGB9 0
#define fujitilesSGB10 0
#define fujitilesSGB11 0
#define fujitilesSGB12 0
#define fujitilesSGB13 0
#define fujitilesSGB14 0
#define fujitilesSGB15 0
#define fujitilesSGB16 0
#define fujitilesSGB17 0
#define fujitilesSGB18 0
#define fujitilesSGB19 0
#define fujitilesSGB20 0
#define fujitilesSGB21 0
#define fujitilesSGB22 0
#define fujitilesSGB23 0
#define fujitilesSGB24 0
#define fujitilesSGB25 0
#define fujitilesSGB26 0
#define fujitilesSGB27 0
#define fujitilesSGB28 0
#define fujitilesSGB29 0
#define fujitilesSGB30 0
#define fujitilesSGB31 0
#define fujitilesSGB32 0
#define fujitilesSGB33 0
#define fujitilesSGB34 0
#define fujitilesSGB35 0
#define fujitilesSGB36 0
#define fujitilesSGB37 0
#define fujitilesSGB38 0
#define fujitilesSGB39 0
#define fujitilesSGB40 0
#define fujitilesSGB41 0
#define fujitilesSGB42 0
#define fujitilesSGB43 0
#define fujitilesSGB44 0
#define fujitilesSGB45 0
#define fujitilesSGB46 0
#define fujitilesSGB47 0
#define fujitilesSGB48 0
#define fujitilesSGB49 0
#define fujitilesSGB50 0
#define fujitilesSGB51 0
#define fujitilesSGB52 0
#define fujitilesSGB53 0
#define fujitilesSGB54 0
#define fujitilesSGB55 0
#define fujitilesSGB56 0
#define fujitilesSGB57 0
#define fujitilesSGB58 0
#define fujitilesSGB59 0
#define fujitilesSGB60 0
#define fujitilesSGB61 0
#define fujitilesSGB62 0
#define fujitilesSGB63 0
#define fujitilesSGB64 0
#define fujitilesSGB65 0
#define fujitilesSGB66 2
#define fujitilesSGB67 2
#define fujitilesSGB68 0
#define fujitilesSGB69 0
#define fujitilesSGB70 0
#define fujitilesSGB71 0
#define fujitilesSGB72 0
#define fujitilesSGB73 0
#define fujitilesSGB74 0
#define fujitilesSGB75 0
#define fujitilesSGB76 0
#define fujitilesSGB77 0
#define fujitilesSGB78 0
#define fujitilesSGB79 0
#define fujitilesSGB80 0
#define fujitilesSGB81 0
#define fujitilesSGB82 0
#define fujitilesSGB83 0
#define fujitilesSGB84 0
#define fujitilesSGB85 0
#define fujitilesSGB86 0
#define fujitilesSGB87 0
#define fujitilesSGB88 0
#define fujitilesSGB89 0
#define fujitilesSGB90 0
#define fujitilesSGB91 0
#define fujitilesSGB92 0
#define fujitilesSGB93 0
#define fujitilesSGB94 0
#define fujitilesSGB95 0
#define fujitilesSGB96 0
#define fujitilesSGB97 0
#define fujitilesSGB98 0
#define fujitilesSGB99 0
#define fujitilesSGB100 0
#define fujitilesSGB101 0
#define fujitilesSGB102 0
#define fujitilesSGB103 0
#define fujitilesSGB104 0
#define fujitilesSGB105 0
#define fujitilesSGB106 0
#define fujitilesSGB107 0
#define fujitilesSGB108 0
#define fujitilesSGB109 0
#define fujitilesSGB110 0
#define fujitilesSGB111 0
#define fujitilesSGB112 0
#define fujitilesSGB113 0
#define fujitilesSGB114 0
#define fujitilesSGB115 0
#define fujitilesSGB116 0
#define fujitilesSGB117 0
#define fujitilesSGB118 0
#define fujitilesSGB119 0
#define fujitilesSGB120 0
#define fujitilesSGB121 0
#define fujitilesSGB122 0
#define fujitilesSGB123 0
#define fujitilesSGB124 0
#define fujitilesSGB125 0
#define fujitilesSGB126 0
#define fujitilesSGB127 0
#define fujitilesSGB128 0
#define fujitilesSGB129 0
#define fujitilesSGB130 0
#define fujitilesSGB131 0
#define fujitilesSGB132 0
#define fujitilesSGB133 0
#define fujitilesSGB134 0
#define fujitilesSGB135 0
#define fujitilesSGB136 0
#define fujitilesSGB137 0
#define fujitilesSGB138 0
#define fujitilesSGB139 0
#define fujitilesSGB140 0
#define fujitilesSGB141 0
#define fujitilesSGB142 0
#define fujitilesSGB143 0
#define fujitilesSGB144 0
#define fujitilesSGB145 0
#define fujitilesSGB146 0
#define fujitilesSGB147 0
#define fujitilesSGB148 0
#define fujitilesSGB149 0
#define fujitilesSGB150 0
#define fujitilesSGB151 0
#define fujitilesSGB152 0
#define fujitilesSGB153 0
#define fujitilesSGB154 0
#define fujitilesSGB155 0
#define fujitilesSGB156 0
#define fujitilesSGB157 0
#define fujitilesSGB158 0
#define fujitilesSGB159 0
#define fujitilesSGB160 0
#define fujitilesSGB161 0
#define fujitilesSGB162 0
#define fujitilesSGB163 0
#define fujitilesSGB164 0
#define fujitilesSGB165 0
/* Start of tile array. */
extern const unsigned char fujitiles[];

#endif

/* End of CUTSCENETILES.H */
