/*

 DEADROOKBLACK.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 8

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __deadrookblack_h_INCLUDE
#define __deadrookblack_h_INCLUDE

/* Bank of tiles. */
#define deadrookraccoonBank 0

/* Super Gameboy palette 0 */
#define deadrookraccoonSGBPal0c0 32767
#define deadrookraccoonSGBPal0c1 16089
#define deadrookraccoonSGBPal0c2 10804
#define deadrookraccoonSGBPal0c3 0

/* Super Gameboy palette 1 */
#define deadrookraccoonSGBPal1c0 32767
#define deadrookraccoonSGBPal1c1 8935
#define deadrookraccoonSGBPal1c2 6596
#define deadrookraccoonSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define deadrookraccoonSGBPal2c0 32767
#define deadrookraccoonSGBPal2c1 8935
#define deadrookraccoonSGBPal2c2 6596
#define deadrookraccoonSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define deadrookraccoonSGBPal3c0 32767
#define deadrookraccoonSGBPal3c1 8935
#define deadrookraccoonSGBPal3c2 6596
#define deadrookraccoonSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define deadrookraccoonCGBPal0c0 6076
#define deadrookraccoonCGBPal0c1 8935
#define deadrookraccoonCGBPal0c2 6596
#define deadrookraccoonCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define deadrookraccoonCGBPal1c0 6076
#define deadrookraccoonCGBPal1c1 8935
#define deadrookraccoonCGBPal1c2 6596
#define deadrookraccoonCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define deadrookraccoonCGBPal2c0 6076
#define deadrookraccoonCGBPal2c1 8935
#define deadrookraccoonCGBPal2c2 6596
#define deadrookraccoonCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define deadrookraccoonCGBPal3c0 6076
#define deadrookraccoonCGBPal3c1 8935
#define deadrookraccoonCGBPal3c2 6596
#define deadrookraccoonCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define deadrookraccoonCGBPal4c0 6076
#define deadrookraccoonCGBPal4c1 8935
#define deadrookraccoonCGBPal4c2 6596
#define deadrookraccoonCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define deadrookraccoonCGBPal5c0 6076
#define deadrookraccoonCGBPal5c1 8935
#define deadrookraccoonCGBPal5c2 6596
#define deadrookraccoonCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define deadrookraccoonCGBPal6c0 6076
#define deadrookraccoonCGBPal6c1 8935
#define deadrookraccoonCGBPal6c2 6596
#define deadrookraccoonCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define deadrookraccoonCGBPal7c0 6076
#define deadrookraccoonCGBPal7c1 8935
#define deadrookraccoonCGBPal7c2 6596
#define deadrookraccoonCGBPal7c3 5344

/* SGB palette entries. */
#define deadrookraccoonSGB0 0
#define deadrookraccoonSGB1 0
#define deadrookraccoonSGB2 0
#define deadrookraccoonSGB3 0
#define deadrookraccoonSGB4 0
#define deadrookraccoonSGB5 0
#define deadrookraccoonSGB6 0
#define deadrookraccoonSGB7 0
#define deadrookraccoonSGB8 0
/* Start of tile array. */
extern const unsigned char deadrookraccoon[];

#endif

/* End of DEADROOKBLACK.H */
