/*

 DEADGOLDWHITE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 8

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __deadgoldwhite_h_INCLUDE
#define __deadgoldwhite_h_INCLUDE

/* Bank of tiles. */
#define deadgoldfoxBank 0

/* Super Gameboy palette 0 */
#define deadgoldfoxSGBPal0c0 32767
#define deadgoldfoxSGBPal0c1 16089
#define deadgoldfoxSGBPal0c2 10804
#define deadgoldfoxSGBPal0c3 0

/* Super Gameboy palette 1 */
#define deadgoldfoxSGBPal1c0 32767
#define deadgoldfoxSGBPal1c1 8935
#define deadgoldfoxSGBPal1c2 6596
#define deadgoldfoxSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define deadgoldfoxSGBPal2c0 32767
#define deadgoldfoxSGBPal2c1 8935
#define deadgoldfoxSGBPal2c2 6596
#define deadgoldfoxSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define deadgoldfoxSGBPal3c0 32767
#define deadgoldfoxSGBPal3c1 8935
#define deadgoldfoxSGBPal3c2 6596
#define deadgoldfoxSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define deadgoldfoxCGBPal0c0 6076
#define deadgoldfoxCGBPal0c1 8935
#define deadgoldfoxCGBPal0c2 6596
#define deadgoldfoxCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define deadgoldfoxCGBPal1c0 6076
#define deadgoldfoxCGBPal1c1 8935
#define deadgoldfoxCGBPal1c2 6596
#define deadgoldfoxCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define deadgoldfoxCGBPal2c0 6076
#define deadgoldfoxCGBPal2c1 8935
#define deadgoldfoxCGBPal2c2 6596
#define deadgoldfoxCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define deadgoldfoxCGBPal3c0 6076
#define deadgoldfoxCGBPal3c1 8935
#define deadgoldfoxCGBPal3c2 6596
#define deadgoldfoxCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define deadgoldfoxCGBPal4c0 6076
#define deadgoldfoxCGBPal4c1 8935
#define deadgoldfoxCGBPal4c2 6596
#define deadgoldfoxCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define deadgoldfoxCGBPal5c0 6076
#define deadgoldfoxCGBPal5c1 8935
#define deadgoldfoxCGBPal5c2 6596
#define deadgoldfoxCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define deadgoldfoxCGBPal6c0 6076
#define deadgoldfoxCGBPal6c1 8935
#define deadgoldfoxCGBPal6c2 6596
#define deadgoldfoxCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define deadgoldfoxCGBPal7c0 6076
#define deadgoldfoxCGBPal7c1 8935
#define deadgoldfoxCGBPal7c2 6596
#define deadgoldfoxCGBPal7c3 5344

/* SGB palette entries. */
#define deadgoldfoxSGB0 0
#define deadgoldfoxSGB1 0
#define deadgoldfoxSGB2 0
#define deadgoldfoxSGB3 0
#define deadgoldfoxSGB4 0
#define deadgoldfoxSGB5 0
#define deadgoldfoxSGB6 0
#define deadgoldfoxSGB7 0
#define deadgoldfoxSGB8 0
/* Start of tile array. */
extern const unsigned char deadgoldfox[];

#endif

/* End of DEADGOLDWHITE.H */
