/*

 DEADROOKWHITE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 8

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __deadrookwhite_h_INCLUDE
#define __deadrookwhite_h_INCLUDE

/* Bank of tiles. */
#define deadrookfoxBank 0

/* Super Gameboy palette 0 */
#define deadrookfoxSGBPal0c0 32767
#define deadrookfoxSGBPal0c1 16089
#define deadrookfoxSGBPal0c2 10804
#define deadrookfoxSGBPal0c3 0

/* Super Gameboy palette 1 */
#define deadrookfoxSGBPal1c0 32767
#define deadrookfoxSGBPal1c1 8935
#define deadrookfoxSGBPal1c2 6596
#define deadrookfoxSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define deadrookfoxSGBPal2c0 32767
#define deadrookfoxSGBPal2c1 8935
#define deadrookfoxSGBPal2c2 6596
#define deadrookfoxSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define deadrookfoxSGBPal3c0 32767
#define deadrookfoxSGBPal3c1 8935
#define deadrookfoxSGBPal3c2 6596
#define deadrookfoxSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define deadrookfoxCGBPal0c0 6076
#define deadrookfoxCGBPal0c1 8935
#define deadrookfoxCGBPal0c2 6596
#define deadrookfoxCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define deadrookfoxCGBPal1c0 6076
#define deadrookfoxCGBPal1c1 8935
#define deadrookfoxCGBPal1c2 6596
#define deadrookfoxCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define deadrookfoxCGBPal2c0 6076
#define deadrookfoxCGBPal2c1 8935
#define deadrookfoxCGBPal2c2 6596
#define deadrookfoxCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define deadrookfoxCGBPal3c0 6076
#define deadrookfoxCGBPal3c1 8935
#define deadrookfoxCGBPal3c2 6596
#define deadrookfoxCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define deadrookfoxCGBPal4c0 6076
#define deadrookfoxCGBPal4c1 8935
#define deadrookfoxCGBPal4c2 6596
#define deadrookfoxCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define deadrookfoxCGBPal5c0 6076
#define deadrookfoxCGBPal5c1 8935
#define deadrookfoxCGBPal5c2 6596
#define deadrookfoxCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define deadrookfoxCGBPal6c0 6076
#define deadrookfoxCGBPal6c1 8935
#define deadrookfoxCGBPal6c2 6596
#define deadrookfoxCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define deadrookfoxCGBPal7c0 6076
#define deadrookfoxCGBPal7c1 8935
#define deadrookfoxCGBPal7c2 6596
#define deadrookfoxCGBPal7c3 5344

/* SGB palette entries. */
#define deadrookfoxSGB0 0
#define deadrookfoxSGB1 0
#define deadrookfoxSGB2 0
#define deadrookfoxSGB3 0
#define deadrookfoxSGB4 0
#define deadrookfoxSGB5 0
#define deadrookfoxSGB6 0
#define deadrookfoxSGB7 0
#define deadrookfoxSGB8 0
/* Start of tile array. */
extern const unsigned char deadrookfox[];

#endif

/* End of DEADROOKWHITE.H */
