/*

 DEADBISHOPWHITE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 8

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __deadbishopwhite_h_INCLUDE
#define __deadbishopwhite_h_INCLUDE

/* Bank of tiles. */
#define deadbishopfoxBank 0

/* Super Gameboy palette 0 */
#define deadbishopfoxSGBPal0c0 32767
#define deadbishopfoxSGBPal0c1 16089
#define deadbishopfoxSGBPal0c2 10804
#define deadbishopfoxSGBPal0c3 0

/* Super Gameboy palette 1 */
#define deadbishopfoxSGBPal1c0 32767
#define deadbishopfoxSGBPal1c1 8935
#define deadbishopfoxSGBPal1c2 6596
#define deadbishopfoxSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define deadbishopfoxSGBPal2c0 32767
#define deadbishopfoxSGBPal2c1 8935
#define deadbishopfoxSGBPal2c2 6596
#define deadbishopfoxSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define deadbishopfoxSGBPal3c0 32767
#define deadbishopfoxSGBPal3c1 8935
#define deadbishopfoxSGBPal3c2 6596
#define deadbishopfoxSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define deadbishopfoxCGBPal0c0 6076
#define deadbishopfoxCGBPal0c1 8935
#define deadbishopfoxCGBPal0c2 6596
#define deadbishopfoxCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define deadbishopfoxCGBPal1c0 6076
#define deadbishopfoxCGBPal1c1 8935
#define deadbishopfoxCGBPal1c2 6596
#define deadbishopfoxCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define deadbishopfoxCGBPal2c0 6076
#define deadbishopfoxCGBPal2c1 8935
#define deadbishopfoxCGBPal2c2 6596
#define deadbishopfoxCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define deadbishopfoxCGBPal3c0 6076
#define deadbishopfoxCGBPal3c1 8935
#define deadbishopfoxCGBPal3c2 6596
#define deadbishopfoxCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define deadbishopfoxCGBPal4c0 6076
#define deadbishopfoxCGBPal4c1 8935
#define deadbishopfoxCGBPal4c2 6596
#define deadbishopfoxCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define deadbishopfoxCGBPal5c0 6076
#define deadbishopfoxCGBPal5c1 8935
#define deadbishopfoxCGBPal5c2 6596
#define deadbishopfoxCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define deadbishopfoxCGBPal6c0 6076
#define deadbishopfoxCGBPal6c1 8935
#define deadbishopfoxCGBPal6c2 6596
#define deadbishopfoxCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define deadbishopfoxCGBPal7c0 6076
#define deadbishopfoxCGBPal7c1 8935
#define deadbishopfoxCGBPal7c2 6596
#define deadbishopfoxCGBPal7c3 5344

/* SGB palette entries. */
#define deadbishopfoxSGB0 0
#define deadbishopfoxSGB1 0
#define deadbishopfoxSGB2 0
#define deadbishopfoxSGB3 0
#define deadbishopfoxSGB4 0
#define deadbishopfoxSGB5 0
#define deadbishopfoxSGB6 0
#define deadbishopfoxSGB7 0
#define deadbishopfoxSGB8 0
/* Start of tile array. */
extern const unsigned char deadbishopfox[];

#endif

/* End of DEADBISHOPWHITE.H */
