/*

 DEADSILVERWHITE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 8

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __deadsilverwhite_h_INCLUDE
#define __deadsilverwhite_h_INCLUDE

/* Bank of tiles. */
#define deadsilverfoxBank 0

/* Super Gameboy palette 0 */
#define deadsilverfoxSGBPal0c0 32767
#define deadsilverfoxSGBPal0c1 16089
#define deadsilverfoxSGBPal0c2 10804
#define deadsilverfoxSGBPal0c3 0

/* Super Gameboy palette 1 */
#define deadsilverfoxSGBPal1c0 32767
#define deadsilverfoxSGBPal1c1 8935
#define deadsilverfoxSGBPal1c2 6596
#define deadsilverfoxSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define deadsilverfoxSGBPal2c0 32767
#define deadsilverfoxSGBPal2c1 8935
#define deadsilverfoxSGBPal2c2 6596
#define deadsilverfoxSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define deadsilverfoxSGBPal3c0 32767
#define deadsilverfoxSGBPal3c1 8935
#define deadsilverfoxSGBPal3c2 6596
#define deadsilverfoxSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define deadsilverfoxCGBPal0c0 6076
#define deadsilverfoxCGBPal0c1 8935
#define deadsilverfoxCGBPal0c2 6596
#define deadsilverfoxCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define deadsilverfoxCGBPal1c0 6076
#define deadsilverfoxCGBPal1c1 8935
#define deadsilverfoxCGBPal1c2 6596
#define deadsilverfoxCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define deadsilverfoxCGBPal2c0 6076
#define deadsilverfoxCGBPal2c1 8935
#define deadsilverfoxCGBPal2c2 6596
#define deadsilverfoxCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define deadsilverfoxCGBPal3c0 6076
#define deadsilverfoxCGBPal3c1 8935
#define deadsilverfoxCGBPal3c2 6596
#define deadsilverfoxCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define deadsilverfoxCGBPal4c0 6076
#define deadsilverfoxCGBPal4c1 8935
#define deadsilverfoxCGBPal4c2 6596
#define deadsilverfoxCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define deadsilverfoxCGBPal5c0 6076
#define deadsilverfoxCGBPal5c1 8935
#define deadsilverfoxCGBPal5c2 6596
#define deadsilverfoxCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define deadsilverfoxCGBPal6c0 6076
#define deadsilverfoxCGBPal6c1 8935
#define deadsilverfoxCGBPal6c2 6596
#define deadsilverfoxCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define deadsilverfoxCGBPal7c0 6076
#define deadsilverfoxCGBPal7c1 8935
#define deadsilverfoxCGBPal7c2 6596
#define deadsilverfoxCGBPal7c3 5344

/* SGB palette entries. */
#define deadsilverfoxSGB0 0
#define deadsilverfoxSGB1 0
#define deadsilverfoxSGB2 0
#define deadsilverfoxSGB3 0
#define deadsilverfoxSGB4 0
#define deadsilverfoxSGB5 0
#define deadsilverfoxSGB6 0
#define deadsilverfoxSGB7 0
#define deadsilverfoxSGB8 0
/* Start of tile array. */
extern const unsigned char deadsilverfox[];

#endif

/* End of DEADSILVERWHITE.H */
