/*

 DEADPAWNWHITE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 8

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __deadpawnwhite_h_INCLUDE
#define __deadpawnwhite_h_INCLUDE

/* Bank of tiles. */
#define deadpawnfoxBank 0

/* Super Gameboy palette 0 */
#define deadpawnfoxSGBPal0c0 32767
#define deadpawnfoxSGBPal0c1 16089
#define deadpawnfoxSGBPal0c2 10804
#define deadpawnfoxSGBPal0c3 0

/* Super Gameboy palette 1 */
#define deadpawnfoxSGBPal1c0 32767
#define deadpawnfoxSGBPal1c1 8935
#define deadpawnfoxSGBPal1c2 6596
#define deadpawnfoxSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define deadpawnfoxSGBPal2c0 32767
#define deadpawnfoxSGBPal2c1 8935
#define deadpawnfoxSGBPal2c2 6596
#define deadpawnfoxSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define deadpawnfoxSGBPal3c0 32767
#define deadpawnfoxSGBPal3c1 8935
#define deadpawnfoxSGBPal3c2 6596
#define deadpawnfoxSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define deadpawnfoxCGBPal0c0 6076
#define deadpawnfoxCGBPal0c1 8935
#define deadpawnfoxCGBPal0c2 6596
#define deadpawnfoxCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define deadpawnfoxCGBPal1c0 6076
#define deadpawnfoxCGBPal1c1 8935
#define deadpawnfoxCGBPal1c2 6596
#define deadpawnfoxCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define deadpawnfoxCGBPal2c0 6076
#define deadpawnfoxCGBPal2c1 8935
#define deadpawnfoxCGBPal2c2 6596
#define deadpawnfoxCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define deadpawnfoxCGBPal3c0 6076
#define deadpawnfoxCGBPal3c1 8935
#define deadpawnfoxCGBPal3c2 6596
#define deadpawnfoxCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define deadpawnfoxCGBPal4c0 6076
#define deadpawnfoxCGBPal4c1 8935
#define deadpawnfoxCGBPal4c2 6596
#define deadpawnfoxCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define deadpawnfoxCGBPal5c0 6076
#define deadpawnfoxCGBPal5c1 8935
#define deadpawnfoxCGBPal5c2 6596
#define deadpawnfoxCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define deadpawnfoxCGBPal6c0 6076
#define deadpawnfoxCGBPal6c1 8935
#define deadpawnfoxCGBPal6c2 6596
#define deadpawnfoxCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define deadpawnfoxCGBPal7c0 6076
#define deadpawnfoxCGBPal7c1 8935
#define deadpawnfoxCGBPal7c2 6596
#define deadpawnfoxCGBPal7c3 5344

/* SGB palette entries. */
#define deadpawnfoxSGB0 0
#define deadpawnfoxSGB1 0
#define deadpawnfoxSGB2 0
#define deadpawnfoxSGB3 0
#define deadpawnfoxSGB4 0
#define deadpawnfoxSGB5 0
#define deadpawnfoxSGB6 0
#define deadpawnfoxSGB7 0
#define deadpawnfoxSGB8 0
/* Start of tile array. */
extern const unsigned char deadpawnfox[];

#endif

/* End of DEADPAWNWHITE.H */
