/*

 DEADSILVERBLACK.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 8

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __deadsilverblack_h_INCLUDE
#define __deadsilverblack_h_INCLUDE

/* Bank of tiles. */
#define deadsilverraccoonBank 0

/* Super Gameboy palette 0 */
#define deadsilverraccoonSGBPal0c0 32767
#define deadsilverraccoonSGBPal0c1 16089
#define deadsilverraccoonSGBPal0c2 10804
#define deadsilverraccoonSGBPal0c3 0

/* Super Gameboy palette 1 */
#define deadsilverraccoonSGBPal1c0 32767
#define deadsilverraccoonSGBPal1c1 8935
#define deadsilverraccoonSGBPal1c2 6596
#define deadsilverraccoonSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define deadsilverraccoonSGBPal2c0 32767
#define deadsilverraccoonSGBPal2c1 8935
#define deadsilverraccoonSGBPal2c2 6596
#define deadsilverraccoonSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define deadsilverraccoonSGBPal3c0 32767
#define deadsilverraccoonSGBPal3c1 8935
#define deadsilverraccoonSGBPal3c2 6596
#define deadsilverraccoonSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define deadsilverraccoonCGBPal0c0 6076
#define deadsilverraccoonCGBPal0c1 8935
#define deadsilverraccoonCGBPal0c2 6596
#define deadsilverraccoonCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define deadsilverraccoonCGBPal1c0 6076
#define deadsilverraccoonCGBPal1c1 8935
#define deadsilverraccoonCGBPal1c2 6596
#define deadsilverraccoonCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define deadsilverraccoonCGBPal2c0 6076
#define deadsilverraccoonCGBPal2c1 8935
#define deadsilverraccoonCGBPal2c2 6596
#define deadsilverraccoonCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define deadsilverraccoonCGBPal3c0 6076
#define deadsilverraccoonCGBPal3c1 8935
#define deadsilverraccoonCGBPal3c2 6596
#define deadsilverraccoonCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define deadsilverraccoonCGBPal4c0 6076
#define deadsilverraccoonCGBPal4c1 8935
#define deadsilverraccoonCGBPal4c2 6596
#define deadsilverraccoonCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define deadsilverraccoonCGBPal5c0 6076
#define deadsilverraccoonCGBPal5c1 8935
#define deadsilverraccoonCGBPal5c2 6596
#define deadsilverraccoonCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define deadsilverraccoonCGBPal6c0 6076
#define deadsilverraccoonCGBPal6c1 8935
#define deadsilverraccoonCGBPal6c2 6596
#define deadsilverraccoonCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define deadsilverraccoonCGBPal7c0 6076
#define deadsilverraccoonCGBPal7c1 8935
#define deadsilverraccoonCGBPal7c2 6596
#define deadsilverraccoonCGBPal7c3 5344

/* SGB palette entries. */
#define deadsilverraccoonSGB0 0
#define deadsilverraccoonSGB1 0
#define deadsilverraccoonSGB2 0
#define deadsilverraccoonSGB3 0
#define deadsilverraccoonSGB4 0
#define deadsilverraccoonSGB5 0
#define deadsilverraccoonSGB6 0
#define deadsilverraccoonSGB7 0
#define deadsilverraccoonSGB8 0
/* Start of tile array. */
extern const unsigned char deadsilverraccoon[];

#endif

/* End of DEADSILVERBLACK.H */
