/*

 DEADPAWNBLACK.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 8

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __deadpawnblack_h_INCLUDE
#define __deadpawnblack_h_INCLUDE

/* Bank of tiles. */
#define deadpawnraccoonBank 0

/* Super Gameboy palette 0 */
#define deadpawnraccoonSGBPal0c0 32767
#define deadpawnraccoonSGBPal0c1 16089
#define deadpawnraccoonSGBPal0c2 10804
#define deadpawnraccoonSGBPal0c3 0

/* Super Gameboy palette 1 */
#define deadpawnraccoonSGBPal1c0 32767
#define deadpawnraccoonSGBPal1c1 8935
#define deadpawnraccoonSGBPal1c2 6596
#define deadpawnraccoonSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define deadpawnraccoonSGBPal2c0 32767
#define deadpawnraccoonSGBPal2c1 8935
#define deadpawnraccoonSGBPal2c2 6596
#define deadpawnraccoonSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define deadpawnraccoonSGBPal3c0 32767
#define deadpawnraccoonSGBPal3c1 8935
#define deadpawnraccoonSGBPal3c2 6596
#define deadpawnraccoonSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define deadpawnraccoonCGBPal0c0 6076
#define deadpawnraccoonCGBPal0c1 8935
#define deadpawnraccoonCGBPal0c2 6596
#define deadpawnraccoonCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define deadpawnraccoonCGBPal1c0 6076
#define deadpawnraccoonCGBPal1c1 8935
#define deadpawnraccoonCGBPal1c2 6596
#define deadpawnraccoonCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define deadpawnraccoonCGBPal2c0 6076
#define deadpawnraccoonCGBPal2c1 8935
#define deadpawnraccoonCGBPal2c2 6596
#define deadpawnraccoonCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define deadpawnraccoonCGBPal3c0 6076
#define deadpawnraccoonCGBPal3c1 8935
#define deadpawnraccoonCGBPal3c2 6596
#define deadpawnraccoonCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define deadpawnraccoonCGBPal4c0 6076
#define deadpawnraccoonCGBPal4c1 8935
#define deadpawnraccoonCGBPal4c2 6596
#define deadpawnraccoonCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define deadpawnraccoonCGBPal5c0 6076
#define deadpawnraccoonCGBPal5c1 8935
#define deadpawnraccoonCGBPal5c2 6596
#define deadpawnraccoonCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define deadpawnraccoonCGBPal6c0 6076
#define deadpawnraccoonCGBPal6c1 8935
#define deadpawnraccoonCGBPal6c2 6596
#define deadpawnraccoonCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define deadpawnraccoonCGBPal7c0 6076
#define deadpawnraccoonCGBPal7c1 8935
#define deadpawnraccoonCGBPal7c2 6596
#define deadpawnraccoonCGBPal7c3 5344

/* SGB palette entries. */
#define deadpawnraccoonSGB0 0
#define deadpawnraccoonSGB1 0
#define deadpawnraccoonSGB2 0
#define deadpawnraccoonSGB3 0
#define deadpawnraccoonSGB4 0
#define deadpawnraccoonSGB5 0
#define deadpawnraccoonSGB6 0
#define deadpawnraccoonSGB7 0
#define deadpawnraccoonSGB8 0
/* Start of tile array. */
extern const unsigned char deadpawnraccoon[];

#endif

/* End of DEADPAWNBLACK.H */
