/*

 DEADBISHOPBLACK.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 8

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __deadbishopblack_h_INCLUDE
#define __deadbishopblack_h_INCLUDE

/* Bank of tiles. */
#define deadbishopraccoonBank 0

/* Super Gameboy palette 0 */
#define deadbishopraccoonSGBPal0c0 32767
#define deadbishopraccoonSGBPal0c1 16089
#define deadbishopraccoonSGBPal0c2 10804
#define deadbishopraccoonSGBPal0c3 0

/* Super Gameboy palette 1 */
#define deadbishopraccoonSGBPal1c0 32767
#define deadbishopraccoonSGBPal1c1 8935
#define deadbishopraccoonSGBPal1c2 6596
#define deadbishopraccoonSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define deadbishopraccoonSGBPal2c0 32767
#define deadbishopraccoonSGBPal2c1 8935
#define deadbishopraccoonSGBPal2c2 6596
#define deadbishopraccoonSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define deadbishopraccoonSGBPal3c0 32767
#define deadbishopraccoonSGBPal3c1 8935
#define deadbishopraccoonSGBPal3c2 6596
#define deadbishopraccoonSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define deadbishopraccoonCGBPal0c0 6076
#define deadbishopraccoonCGBPal0c1 8935
#define deadbishopraccoonCGBPal0c2 6596
#define deadbishopraccoonCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define deadbishopraccoonCGBPal1c0 6076
#define deadbishopraccoonCGBPal1c1 8935
#define deadbishopraccoonCGBPal1c2 6596
#define deadbishopraccoonCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define deadbishopraccoonCGBPal2c0 6076
#define deadbishopraccoonCGBPal2c1 8935
#define deadbishopraccoonCGBPal2c2 6596
#define deadbishopraccoonCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define deadbishopraccoonCGBPal3c0 6076
#define deadbishopraccoonCGBPal3c1 8935
#define deadbishopraccoonCGBPal3c2 6596
#define deadbishopraccoonCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define deadbishopraccoonCGBPal4c0 6076
#define deadbishopraccoonCGBPal4c1 8935
#define deadbishopraccoonCGBPal4c2 6596
#define deadbishopraccoonCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define deadbishopraccoonCGBPal5c0 6076
#define deadbishopraccoonCGBPal5c1 8935
#define deadbishopraccoonCGBPal5c2 6596
#define deadbishopraccoonCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define deadbishopraccoonCGBPal6c0 6076
#define deadbishopraccoonCGBPal6c1 8935
#define deadbishopraccoonCGBPal6c2 6596
#define deadbishopraccoonCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define deadbishopraccoonCGBPal7c0 6076
#define deadbishopraccoonCGBPal7c1 8935
#define deadbishopraccoonCGBPal7c2 6596
#define deadbishopraccoonCGBPal7c3 5344

/* SGB palette entries. */
#define deadbishopraccoonSGB0 0
#define deadbishopraccoonSGB1 0
#define deadbishopraccoonSGB2 0
#define deadbishopraccoonSGB3 0
#define deadbishopraccoonSGB4 0
#define deadbishopraccoonSGB5 0
#define deadbishopraccoonSGB6 0
#define deadbishopraccoonSGB7 0
#define deadbishopraccoonSGB8 0
/* Start of tile array. */
extern const unsigned char deadbishopraccoon[];

#endif

/* End of DEADBISHOPBLACK.H */
