/*

 DEADGOLDBLACK.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 8

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __deadgoldblack_h_INCLUDE
#define __deadgoldblack_h_INCLUDE

/* Bank of tiles. */
#define deadgoldraccoonBank 0

/* Super Gameboy palette 0 */
#define deadgoldraccoonSGBPal0c0 32767
#define deadgoldraccoonSGBPal0c1 16089
#define deadgoldraccoonSGBPal0c2 10804
#define deadgoldraccoonSGBPal0c3 0

/* Super Gameboy palette 1 */
#define deadgoldraccoonSGBPal1c0 32767
#define deadgoldraccoonSGBPal1c1 8935
#define deadgoldraccoonSGBPal1c2 6596
#define deadgoldraccoonSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define deadgoldraccoonSGBPal2c0 32767
#define deadgoldraccoonSGBPal2c1 8935
#define deadgoldraccoonSGBPal2c2 6596
#define deadgoldraccoonSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define deadgoldraccoonSGBPal3c0 32767
#define deadgoldraccoonSGBPal3c1 8935
#define deadgoldraccoonSGBPal3c2 6596
#define deadgoldraccoonSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define deadgoldraccoonCGBPal0c0 6076
#define deadgoldraccoonCGBPal0c1 8935
#define deadgoldraccoonCGBPal0c2 6596
#define deadgoldraccoonCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define deadgoldraccoonCGBPal1c0 6076
#define deadgoldraccoonCGBPal1c1 8935
#define deadgoldraccoonCGBPal1c2 6596
#define deadgoldraccoonCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define deadgoldraccoonCGBPal2c0 6076
#define deadgoldraccoonCGBPal2c1 8935
#define deadgoldraccoonCGBPal2c2 6596
#define deadgoldraccoonCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define deadgoldraccoonCGBPal3c0 6076
#define deadgoldraccoonCGBPal3c1 8935
#define deadgoldraccoonCGBPal3c2 6596
#define deadgoldraccoonCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define deadgoldraccoonCGBPal4c0 6076
#define deadgoldraccoonCGBPal4c1 8935
#define deadgoldraccoonCGBPal4c2 6596
#define deadgoldraccoonCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define deadgoldraccoonCGBPal5c0 6076
#define deadgoldraccoonCGBPal5c1 8935
#define deadgoldraccoonCGBPal5c2 6596
#define deadgoldraccoonCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define deadgoldraccoonCGBPal6c0 6076
#define deadgoldraccoonCGBPal6c1 8935
#define deadgoldraccoonCGBPal6c2 6596
#define deadgoldraccoonCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define deadgoldraccoonCGBPal7c0 6076
#define deadgoldraccoonCGBPal7c1 8935
#define deadgoldraccoonCGBPal7c2 6596
#define deadgoldraccoonCGBPal7c3 5344

/* SGB palette entries. */
#define deadgoldraccoonSGB0 0
#define deadgoldraccoonSGB1 0
#define deadgoldraccoonSGB2 0
#define deadgoldraccoonSGB3 0
#define deadgoldraccoonSGB4 0
#define deadgoldraccoonSGB5 0
#define deadgoldraccoonSGB6 0
#define deadgoldraccoonSGB7 0
#define deadgoldraccoonSGB8 0
/* Start of tile array. */
extern const unsigned char deadgoldraccoon[];

#endif

/* End of DEADGOLDBLACK.H */
