/*

 EDVINDRAWINTRO.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\EdvinDraw\Documents\CosmoCat\Introfield.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __edvindrawintro_h_INCLUDE
#define __edvindrawintro_h_INCLUDE

#define edvindrawWidth 20
#define edvindrawHeight 18
#define edvindrawBank 0

#define edvindraw edvindrawPLN0
extern const unsigned char edvindrawPLN0[];

#endif

/* End of EDVINDRAWINTRO.H */
