/*

 FLASHINGSTAR.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 12

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __flashingstar_h_INCLUDE
#define __flashingstar_h_INCLUDE

/* Bank of tiles. */
#define flashstarBank 0

/* Super Gameboy palette 0 */
#define flashstarSGBPal0c0 32767
#define flashstarSGBPal0c1 32728
#define flashstarSGBPal0c2 22148
#define flashstarSGBPal0c3 0

/* Super Gameboy palette 1 */
#define flashstarSGBPal1c0 32767
#define flashstarSGBPal1c1 8935
#define flashstarSGBPal1c2 6596
#define flashstarSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define flashstarSGBPal2c0 32767
#define flashstarSGBPal2c1 8935
#define flashstarSGBPal2c2 6596
#define flashstarSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define flashstarSGBPal3c0 32767
#define flashstarSGBPal3c1 8935
#define flashstarSGBPal3c2 6596
#define flashstarSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define flashstarCGBPal0c0 6076
#define flashstarCGBPal0c1 8935
#define flashstarCGBPal0c2 6596
#define flashstarCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define flashstarCGBPal1c0 6076
#define flashstarCGBPal1c1 8935
#define flashstarCGBPal1c2 6596
#define flashstarCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define flashstarCGBPal2c0 6076
#define flashstarCGBPal2c1 8935
#define flashstarCGBPal2c2 6596
#define flashstarCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define flashstarCGBPal3c0 6076
#define flashstarCGBPal3c1 8935
#define flashstarCGBPal3c2 6596
#define flashstarCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define flashstarCGBPal4c0 6076
#define flashstarCGBPal4c1 8935
#define flashstarCGBPal4c2 6596
#define flashstarCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define flashstarCGBPal5c0 6076
#define flashstarCGBPal5c1 8935
#define flashstarCGBPal5c2 6596
#define flashstarCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define flashstarCGBPal6c0 6076
#define flashstarCGBPal6c1 8935
#define flashstarCGBPal6c2 6596
#define flashstarCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define flashstarCGBPal7c0 6076
#define flashstarCGBPal7c1 8935
#define flashstarCGBPal7c2 6596
#define flashstarCGBPal7c3 5344

/* SGB palette entries. */
#define flashstarSGB0 0
#define flashstarSGB1 0
#define flashstarSGB2 0
#define flashstarSGB3 0
#define flashstarSGB4 0
#define flashstarSGB5 0
#define flashstarSGB6 0
#define flashstarSGB7 0
#define flashstarSGB8 0
#define flashstarSGB9 0
#define flashstarSGB10 0
#define flashstarSGB11 0
#define flashstarSGB12 0
/* Start of tile array. */
extern const unsigned char flashstar[];

#endif

/* End of FLASHINGSTAR.H */
