/*

 FOXBISHOP1.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 14

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __foxbishop1_h_INCLUDE
#define __foxbishop1_h_INCLUDE

/* Bank of tiles. */
#define shiroikakugyo1Bank 0

/* Super Gameboy palette 0 */
#define shiroikakugyo1SGBPal0c0 32767
#define shiroikakugyo1SGBPal0c1 8728
#define shiroikakugyo1SGBPal0c2 140
#define shiroikakugyo1SGBPal0c3 0

/* Super Gameboy palette 1 */
#define shiroikakugyo1SGBPal1c0 32767
#define shiroikakugyo1SGBPal1c1 671
#define shiroikakugyo1SGBPal1c2 408
#define shiroikakugyo1SGBPal1c3 0

/* Super Gameboy palette 2 */
#define shiroikakugyo1SGBPal2c0 32767
#define shiroikakugyo1SGBPal2c1 8935
#define shiroikakugyo1SGBPal2c2 6596
#define shiroikakugyo1SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define shiroikakugyo1SGBPal3c0 32767
#define shiroikakugyo1SGBPal3c1 8935
#define shiroikakugyo1SGBPal3c2 6596
#define shiroikakugyo1SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define shiroikakugyo1CGBPal0c0 6076
#define shiroikakugyo1CGBPal0c1 8935
#define shiroikakugyo1CGBPal0c2 6596
#define shiroikakugyo1CGBPal0c3 5344

/* Gameboy Color palette 1 */
#define shiroikakugyo1CGBPal1c0 6076
#define shiroikakugyo1CGBPal1c1 8935
#define shiroikakugyo1CGBPal1c2 6596
#define shiroikakugyo1CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define shiroikakugyo1CGBPal2c0 6076
#define shiroikakugyo1CGBPal2c1 8935
#define shiroikakugyo1CGBPal2c2 6596
#define shiroikakugyo1CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define shiroikakugyo1CGBPal3c0 6076
#define shiroikakugyo1CGBPal3c1 8935
#define shiroikakugyo1CGBPal3c2 6596
#define shiroikakugyo1CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define shiroikakugyo1CGBPal4c0 6076
#define shiroikakugyo1CGBPal4c1 8935
#define shiroikakugyo1CGBPal4c2 6596
#define shiroikakugyo1CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define shiroikakugyo1CGBPal5c0 6076
#define shiroikakugyo1CGBPal5c1 8935
#define shiroikakugyo1CGBPal5c2 6596
#define shiroikakugyo1CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define shiroikakugyo1CGBPal6c0 6076
#define shiroikakugyo1CGBPal6c1 8935
#define shiroikakugyo1CGBPal6c2 6596
#define shiroikakugyo1CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define shiroikakugyo1CGBPal7c0 6076
#define shiroikakugyo1CGBPal7c1 8935
#define shiroikakugyo1CGBPal7c2 6596
#define shiroikakugyo1CGBPal7c3 5344

/* SGB palette entries. */
#define shiroikakugyo1SGB0 1
#define shiroikakugyo1SGB1 1
#define shiroikakugyo1SGB2 1
#define shiroikakugyo1SGB3 1
#define shiroikakugyo1SGB4 1
#define shiroikakugyo1SGB5 1
#define shiroikakugyo1SGB6 1
#define shiroikakugyo1SGB7 1
#define shiroikakugyo1SGB8 1
#define shiroikakugyo1SGB9 1
#define shiroikakugyo1SGB10 1
#define shiroikakugyo1SGB11 1
#define shiroikakugyo1SGB12 1
#define shiroikakugyo1SGB13 1
#define shiroikakugyo1SGB14 1
/* Start of tile array. */
extern const unsigned char shiroikakugyo1[];

#endif

/* End of FOXBISHOP1.H */
