/*

 FOXBISHOP2.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 12

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __foxbishop2_h_INCLUDE
#define __foxbishop2_h_INCLUDE

/* Bank of tiles. */
#define shiroikakugyo2Bank 0

/* Super Gameboy palette 0 */
#define shiroikakugyo2SGBPal0c0 32767
#define shiroikakugyo2SGBPal0c1 8728
#define shiroikakugyo2SGBPal0c2 140
#define shiroikakugyo2SGBPal0c3 0

/* Super Gameboy palette 1 */
#define shiroikakugyo2SGBPal1c0 32767
#define shiroikakugyo2SGBPal1c1 671
#define shiroikakugyo2SGBPal1c2 408
#define shiroikakugyo2SGBPal1c3 0

/* Super Gameboy palette 2 */
#define shiroikakugyo2SGBPal2c0 32767
#define shiroikakugyo2SGBPal2c1 8935
#define shiroikakugyo2SGBPal2c2 6596
#define shiroikakugyo2SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define shiroikakugyo2SGBPal3c0 32767
#define shiroikakugyo2SGBPal3c1 8935
#define shiroikakugyo2SGBPal3c2 6596
#define shiroikakugyo2SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define shiroikakugyo2CGBPal0c0 6076
#define shiroikakugyo2CGBPal0c1 8935
#define shiroikakugyo2CGBPal0c2 6596
#define shiroikakugyo2CGBPal0c3 5344

/* Gameboy Color palette 1 */
#define shiroikakugyo2CGBPal1c0 6076
#define shiroikakugyo2CGBPal1c1 8935
#define shiroikakugyo2CGBPal1c2 6596
#define shiroikakugyo2CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define shiroikakugyo2CGBPal2c0 6076
#define shiroikakugyo2CGBPal2c1 8935
#define shiroikakugyo2CGBPal2c2 6596
#define shiroikakugyo2CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define shiroikakugyo2CGBPal3c0 6076
#define shiroikakugyo2CGBPal3c1 8935
#define shiroikakugyo2CGBPal3c2 6596
#define shiroikakugyo2CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define shiroikakugyo2CGBPal4c0 6076
#define shiroikakugyo2CGBPal4c1 8935
#define shiroikakugyo2CGBPal4c2 6596
#define shiroikakugyo2CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define shiroikakugyo2CGBPal5c0 6076
#define shiroikakugyo2CGBPal5c1 8935
#define shiroikakugyo2CGBPal5c2 6596
#define shiroikakugyo2CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define shiroikakugyo2CGBPal6c0 6076
#define shiroikakugyo2CGBPal6c1 8935
#define shiroikakugyo2CGBPal6c2 6596
#define shiroikakugyo2CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define shiroikakugyo2CGBPal7c0 6076
#define shiroikakugyo2CGBPal7c1 8935
#define shiroikakugyo2CGBPal7c2 6596
#define shiroikakugyo2CGBPal7c3 5344

/* SGB palette entries. */
#define shiroikakugyo2SGB0 1
#define shiroikakugyo2SGB1 1
#define shiroikakugyo2SGB2 1
#define shiroikakugyo2SGB3 1
#define shiroikakugyo2SGB4 1
#define shiroikakugyo2SGB5 1
#define shiroikakugyo2SGB6 1
#define shiroikakugyo2SGB7 1
#define shiroikakugyo2SGB8 1
#define shiroikakugyo2SGB9 1
#define shiroikakugyo2SGB10 1
#define shiroikakugyo2SGB11 1
#define shiroikakugyo2SGB12 1
/* Start of tile array. */
extern const unsigned char shiroikakugyo2[];

#endif

/* End of FOXBISHOP2.H */
