/*

 FOXDOWN.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 10

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __foxdown_h_INCLUDE
#define __foxdown_h_INCLUDE

/* Bank of tiles. */
#define shiroidefeatedBank 0

/* Super Gameboy palette 0 */
#define shiroidefeatedSGBPal0c0 32767
#define shiroidefeatedSGBPal0c1 8728
#define shiroidefeatedSGBPal0c2 140
#define shiroidefeatedSGBPal0c3 0

/* Super Gameboy palette 1 */
#define shiroidefeatedSGBPal1c0 32767
#define shiroidefeatedSGBPal1c1 671
#define shiroidefeatedSGBPal1c2 408
#define shiroidefeatedSGBPal1c3 0

/* Super Gameboy palette 2 */
#define shiroidefeatedSGBPal2c0 32767
#define shiroidefeatedSGBPal2c1 8935
#define shiroidefeatedSGBPal2c2 6596
#define shiroidefeatedSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define shiroidefeatedSGBPal3c0 32767
#define shiroidefeatedSGBPal3c1 8935
#define shiroidefeatedSGBPal3c2 6596
#define shiroidefeatedSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define shiroidefeatedCGBPal0c0 6076
#define shiroidefeatedCGBPal0c1 8935
#define shiroidefeatedCGBPal0c2 6596
#define shiroidefeatedCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define shiroidefeatedCGBPal1c0 6076
#define shiroidefeatedCGBPal1c1 8935
#define shiroidefeatedCGBPal1c2 6596
#define shiroidefeatedCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define shiroidefeatedCGBPal2c0 6076
#define shiroidefeatedCGBPal2c1 8935
#define shiroidefeatedCGBPal2c2 6596
#define shiroidefeatedCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define shiroidefeatedCGBPal3c0 6076
#define shiroidefeatedCGBPal3c1 8935
#define shiroidefeatedCGBPal3c2 6596
#define shiroidefeatedCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define shiroidefeatedCGBPal4c0 6076
#define shiroidefeatedCGBPal4c1 8935
#define shiroidefeatedCGBPal4c2 6596
#define shiroidefeatedCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define shiroidefeatedCGBPal5c0 6076
#define shiroidefeatedCGBPal5c1 8935
#define shiroidefeatedCGBPal5c2 6596
#define shiroidefeatedCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define shiroidefeatedCGBPal6c0 6076
#define shiroidefeatedCGBPal6c1 8935
#define shiroidefeatedCGBPal6c2 6596
#define shiroidefeatedCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define shiroidefeatedCGBPal7c0 6076
#define shiroidefeatedCGBPal7c1 8935
#define shiroidefeatedCGBPal7c2 6596
#define shiroidefeatedCGBPal7c3 5344

/* SGB palette entries. */
#define shiroidefeatedSGB0 1
#define shiroidefeatedSGB1 1
#define shiroidefeatedSGB2 1
#define shiroidefeatedSGB3 1
#define shiroidefeatedSGB4 1
#define shiroidefeatedSGB5 1
#define shiroidefeatedSGB6 1
#define shiroidefeatedSGB7 1
#define shiroidefeatedSGB8 1
#define shiroidefeatedSGB9 1
#define shiroidefeatedSGB10 1
/* Start of tile array. */
extern const unsigned char shiroidefeated[];

#endif

/* End of FOXDOWN.H */
