/*

 FOXGOLD1.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 14

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __foxgold1_h_INCLUDE
#define __foxgold1_h_INCLUDE

/* Bank of tiles. */
#define shiroikinshou1Bank 0

/* Super Gameboy palette 0 */
#define shiroikinshou1SGBPal0c0 32767
#define shiroikinshou1SGBPal0c1 8728
#define shiroikinshou1SGBPal0c2 140
#define shiroikinshou1SGBPal0c3 0

/* Super Gameboy palette 1 */
#define shiroikinshou1SGBPal1c0 32767
#define shiroikinshou1SGBPal1c1 671
#define shiroikinshou1SGBPal1c2 408
#define shiroikinshou1SGBPal1c3 0

/* Super Gameboy palette 2 */
#define shiroikinshou1SGBPal2c0 32767
#define shiroikinshou1SGBPal2c1 8935
#define shiroikinshou1SGBPal2c2 6596
#define shiroikinshou1SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define shiroikinshou1SGBPal3c0 32767
#define shiroikinshou1SGBPal3c1 8935
#define shiroikinshou1SGBPal3c2 6596
#define shiroikinshou1SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define shiroikinshou1CGBPal0c0 6076
#define shiroikinshou1CGBPal0c1 8935
#define shiroikinshou1CGBPal0c2 6596
#define shiroikinshou1CGBPal0c3 5344

/* Gameboy Color palette 1 */
#define shiroikinshou1CGBPal1c0 6076
#define shiroikinshou1CGBPal1c1 8935
#define shiroikinshou1CGBPal1c2 6596
#define shiroikinshou1CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define shiroikinshou1CGBPal2c0 6076
#define shiroikinshou1CGBPal2c1 8935
#define shiroikinshou1CGBPal2c2 6596
#define shiroikinshou1CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define shiroikinshou1CGBPal3c0 6076
#define shiroikinshou1CGBPal3c1 8935
#define shiroikinshou1CGBPal3c2 6596
#define shiroikinshou1CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define shiroikinshou1CGBPal4c0 6076
#define shiroikinshou1CGBPal4c1 8935
#define shiroikinshou1CGBPal4c2 6596
#define shiroikinshou1CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define shiroikinshou1CGBPal5c0 6076
#define shiroikinshou1CGBPal5c1 8935
#define shiroikinshou1CGBPal5c2 6596
#define shiroikinshou1CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define shiroikinshou1CGBPal6c0 6076
#define shiroikinshou1CGBPal6c1 8935
#define shiroikinshou1CGBPal6c2 6596
#define shiroikinshou1CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define shiroikinshou1CGBPal7c0 6076
#define shiroikinshou1CGBPal7c1 8935
#define shiroikinshou1CGBPal7c2 6596
#define shiroikinshou1CGBPal7c3 5344

/* SGB palette entries. */
#define shiroikinshou1SGB0 1
#define shiroikinshou1SGB1 1
#define shiroikinshou1SGB2 1
#define shiroikinshou1SGB3 1
#define shiroikinshou1SGB4 1
#define shiroikinshou1SGB5 1
#define shiroikinshou1SGB6 1
#define shiroikinshou1SGB7 1
#define shiroikinshou1SGB8 1
#define shiroikinshou1SGB9 1
#define shiroikinshou1SGB10 1
#define shiroikinshou1SGB11 1
#define shiroikinshou1SGB12 1
#define shiroikinshou1SGB13 1
#define shiroikinshou1SGB14 1
/* Start of tile array. */
extern const unsigned char shiroikinshou1[];

#endif

/* End of FOXGOLD1.H */
