/*

 FOXGOLD2.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 13

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __foxgold2_h_INCLUDE
#define __foxgold2_h_INCLUDE

/* Bank of tiles. */
#define shiroikinshou2Bank 0

/* Super Gameboy palette 0 */
#define shiroikinshou2SGBPal0c0 32767
#define shiroikinshou2SGBPal0c1 8728
#define shiroikinshou2SGBPal0c2 140
#define shiroikinshou2SGBPal0c3 0

/* Super Gameboy palette 1 */
#define shiroikinshou2SGBPal1c0 32767
#define shiroikinshou2SGBPal1c1 671
#define shiroikinshou2SGBPal1c2 408
#define shiroikinshou2SGBPal1c3 0

/* Super Gameboy palette 2 */
#define shiroikinshou2SGBPal2c0 32767
#define shiroikinshou2SGBPal2c1 8935
#define shiroikinshou2SGBPal2c2 6596
#define shiroikinshou2SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define shiroikinshou2SGBPal3c0 32767
#define shiroikinshou2SGBPal3c1 8935
#define shiroikinshou2SGBPal3c2 6596
#define shiroikinshou2SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define shiroikinshou2CGBPal0c0 6076
#define shiroikinshou2CGBPal0c1 8935
#define shiroikinshou2CGBPal0c2 6596
#define shiroikinshou2CGBPal0c3 5344

/* Gameboy Color palette 1 */
#define shiroikinshou2CGBPal1c0 6076
#define shiroikinshou2CGBPal1c1 8935
#define shiroikinshou2CGBPal1c2 6596
#define shiroikinshou2CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define shiroikinshou2CGBPal2c0 6076
#define shiroikinshou2CGBPal2c1 8935
#define shiroikinshou2CGBPal2c2 6596
#define shiroikinshou2CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define shiroikinshou2CGBPal3c0 6076
#define shiroikinshou2CGBPal3c1 8935
#define shiroikinshou2CGBPal3c2 6596
#define shiroikinshou2CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define shiroikinshou2CGBPal4c0 6076
#define shiroikinshou2CGBPal4c1 8935
#define shiroikinshou2CGBPal4c2 6596
#define shiroikinshou2CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define shiroikinshou2CGBPal5c0 6076
#define shiroikinshou2CGBPal5c1 8935
#define shiroikinshou2CGBPal5c2 6596
#define shiroikinshou2CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define shiroikinshou2CGBPal6c0 6076
#define shiroikinshou2CGBPal6c1 8935
#define shiroikinshou2CGBPal6c2 6596
#define shiroikinshou2CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define shiroikinshou2CGBPal7c0 6076
#define shiroikinshou2CGBPal7c1 8935
#define shiroikinshou2CGBPal7c2 6596
#define shiroikinshou2CGBPal7c3 5344

/* SGB palette entries. */
#define shiroikinshou2SGB0 1
#define shiroikinshou2SGB1 1
#define shiroikinshou2SGB2 1
#define shiroikinshou2SGB3 1
#define shiroikinshou2SGB4 1
#define shiroikinshou2SGB5 1
#define shiroikinshou2SGB6 1
#define shiroikinshou2SGB7 1
#define shiroikinshou2SGB8 1
#define shiroikinshou2SGB9 1
#define shiroikinshou2SGB10 1
#define shiroikinshou2SGB11 1
#define shiroikinshou2SGB12 1
#define shiroikinshou2SGB13 1
/* Start of tile array. */
extern const unsigned char shiroikinshou2[];

#endif

/* End of FOXGOLD2.H */
