/*

 FOXKING1.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 12

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __foxking1_h_INCLUDE
#define __foxking1_h_INCLUDE

/* Bank of tiles. */
#define shiroiooshou1Bank 0

/* Super Gameboy palette 0 */
#define shiroiooshou1SGBPal0c0 32767
#define shiroiooshou1SGBPal0c1 8728
#define shiroiooshou1SGBPal0c2 140
#define shiroiooshou1SGBPal0c3 0

/* Super Gameboy palette 1 */
#define shiroiooshou1SGBPal1c0 32767
#define shiroiooshou1SGBPal1c1 671
#define shiroiooshou1SGBPal1c2 408
#define shiroiooshou1SGBPal1c3 0

/* Super Gameboy palette 2 */
#define shiroiooshou1SGBPal2c0 32767
#define shiroiooshou1SGBPal2c1 8935
#define shiroiooshou1SGBPal2c2 6596
#define shiroiooshou1SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define shiroiooshou1SGBPal3c0 32767
#define shiroiooshou1SGBPal3c1 8935
#define shiroiooshou1SGBPal3c2 6596
#define shiroiooshou1SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define shiroiooshou1CGBPal0c0 6076
#define shiroiooshou1CGBPal0c1 8935
#define shiroiooshou1CGBPal0c2 6596
#define shiroiooshou1CGBPal0c3 5344

/* Gameboy Color palette 1 */
#define shiroiooshou1CGBPal1c0 6076
#define shiroiooshou1CGBPal1c1 8935
#define shiroiooshou1CGBPal1c2 6596
#define shiroiooshou1CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define shiroiooshou1CGBPal2c0 6076
#define shiroiooshou1CGBPal2c1 8935
#define shiroiooshou1CGBPal2c2 6596
#define shiroiooshou1CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define shiroiooshou1CGBPal3c0 6076
#define shiroiooshou1CGBPal3c1 8935
#define shiroiooshou1CGBPal3c2 6596
#define shiroiooshou1CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define shiroiooshou1CGBPal4c0 6076
#define shiroiooshou1CGBPal4c1 8935
#define shiroiooshou1CGBPal4c2 6596
#define shiroiooshou1CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define shiroiooshou1CGBPal5c0 6076
#define shiroiooshou1CGBPal5c1 8935
#define shiroiooshou1CGBPal5c2 6596
#define shiroiooshou1CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define shiroiooshou1CGBPal6c0 6076
#define shiroiooshou1CGBPal6c1 8935
#define shiroiooshou1CGBPal6c2 6596
#define shiroiooshou1CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define shiroiooshou1CGBPal7c0 6076
#define shiroiooshou1CGBPal7c1 8935
#define shiroiooshou1CGBPal7c2 6596
#define shiroiooshou1CGBPal7c3 5344

/* SGB palette entries. */
#define shiroiooshou1SGB0 1
#define shiroiooshou1SGB1 1
#define shiroiooshou1SGB2 1
#define shiroiooshou1SGB3 1
#define shiroiooshou1SGB4 1
#define shiroiooshou1SGB5 1
#define shiroiooshou1SGB6 1
#define shiroiooshou1SGB7 1
#define shiroiooshou1SGB8 1
#define shiroiooshou1SGB9 1
#define shiroiooshou1SGB10 1
#define shiroiooshou1SGB11 1
#define shiroiooshou1SGB12 1
/* Start of tile array. */
extern const unsigned char shiroiooshou1[];

#endif

/* End of FOXKING1.H */
