/*

 FUJIYAMA.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : E:\Projects\GoGoShogi\Fuji.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __fujiyama_h_INCLUDE
#define __fujiyama_h_INCLUDE

#define fujisceneWidth 20
#define fujisceneHeight 18
#define fujisceneBank 0

#define fujiscene fujiscenePLN0
extern const unsigned char fujiscenePLN0[];

#endif

/* End of FUJIYAMA.H */
