/*

 GENERALATTACK.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : E:\Projects\GoGoShogi\Fuji.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __generalattack_h_INCLUDE
#define __generalattack_h_INCLUDE

#define blackmapWidth 20
#define blackmapHeight 18
#define blackmapBank 0

#define blackmap blackmapPLN0
extern const unsigned char blackmapPLN0[];

#endif

/* End of GENERALATTACK.H */
