/*

 INTROFIELD.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 69

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Introfield_h_INCLUDE
#define __Introfield_h_INCLUDE

/* Bank of tiles. */
#define IntrotilesBank 0

/* Super Gameboy palette 0 */
#define IntrotilesSGBPal0c0 32767
#define IntrotilesSGBPal0c1 16191
#define IntrotilesSGBPal0c2 26
#define IntrotilesSGBPal0c3 0

/* Super Gameboy palette 1 */
#define IntrotilesSGBPal1c0 32767
#define IntrotilesSGBPal1c1 5790
#define IntrotilesSGBPal1c2 31360
#define IntrotilesSGBPal1c3 0

/* Super Gameboy palette 2 */
#define IntrotilesSGBPal2c0 32767
#define IntrotilesSGBPal2c1 8935
#define IntrotilesSGBPal2c2 6596
#define IntrotilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define IntrotilesSGBPal3c0 32767
#define IntrotilesSGBPal3c1 8935
#define IntrotilesSGBPal3c2 6596
#define IntrotilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define IntrotilesCGBPal0c0 6076
#define IntrotilesCGBPal0c1 8935
#define IntrotilesCGBPal0c2 6596
#define IntrotilesCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define IntrotilesCGBPal1c0 6076
#define IntrotilesCGBPal1c1 8935
#define IntrotilesCGBPal1c2 6596
#define IntrotilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define IntrotilesCGBPal2c0 6076
#define IntrotilesCGBPal2c1 8935
#define IntrotilesCGBPal2c2 6596
#define IntrotilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define IntrotilesCGBPal3c0 6076
#define IntrotilesCGBPal3c1 8935
#define IntrotilesCGBPal3c2 6596
#define IntrotilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define IntrotilesCGBPal4c0 6076
#define IntrotilesCGBPal4c1 8935
#define IntrotilesCGBPal4c2 6596
#define IntrotilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define IntrotilesCGBPal5c0 6076
#define IntrotilesCGBPal5c1 8935
#define IntrotilesCGBPal5c2 6596
#define IntrotilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define IntrotilesCGBPal6c0 6076
#define IntrotilesCGBPal6c1 8935
#define IntrotilesCGBPal6c2 6596
#define IntrotilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define IntrotilesCGBPal7c0 6076
#define IntrotilesCGBPal7c1 8935
#define IntrotilesCGBPal7c2 6596
#define IntrotilesCGBPal7c3 5344

/* SGB palette entries. */
#define IntrotilesSGB0 0
#define IntrotilesSGB1 0
#define IntrotilesSGB2 0
#define IntrotilesSGB3 0
#define IntrotilesSGB4 0
#define IntrotilesSGB5 0
#define IntrotilesSGB6 0
#define IntrotilesSGB7 0
#define IntrotilesSGB8 0
#define IntrotilesSGB9 0
#define IntrotilesSGB10 0
#define IntrotilesSGB11 0
#define IntrotilesSGB12 0
#define IntrotilesSGB13 0
#define IntrotilesSGB14 0
#define IntrotilesSGB15 0
#define IntrotilesSGB16 0
#define IntrotilesSGB17 0
#define IntrotilesSGB18 0
#define IntrotilesSGB19 0
#define IntrotilesSGB20 0
#define IntrotilesSGB21 0
#define IntrotilesSGB22 0
#define IntrotilesSGB23 0
#define IntrotilesSGB24 0
#define IntrotilesSGB25 0
#define IntrotilesSGB26 0
#define IntrotilesSGB27 0
#define IntrotilesSGB28 0
#define IntrotilesSGB29 0
#define IntrotilesSGB30 0
#define IntrotilesSGB31 0
#define IntrotilesSGB32 0
#define IntrotilesSGB33 0
#define IntrotilesSGB34 0
#define IntrotilesSGB35 0
#define IntrotilesSGB36 0
#define IntrotilesSGB37 0
#define IntrotilesSGB38 0
#define IntrotilesSGB39 0
#define IntrotilesSGB40 0
#define IntrotilesSGB41 0
#define IntrotilesSGB42 0
#define IntrotilesSGB43 0
#define IntrotilesSGB44 0
#define IntrotilesSGB45 0
#define IntrotilesSGB46 0
#define IntrotilesSGB47 0
#define IntrotilesSGB48 0
#define IntrotilesSGB49 0
#define IntrotilesSGB50 0
#define IntrotilesSGB51 0
#define IntrotilesSGB52 0
#define IntrotilesSGB53 0
#define IntrotilesSGB54 0
#define IntrotilesSGB55 0
#define IntrotilesSGB56 0
#define IntrotilesSGB57 0
#define IntrotilesSGB58 0
#define IntrotilesSGB59 0
#define IntrotilesSGB60 0
#define IntrotilesSGB61 0
#define IntrotilesSGB62 0
#define IntrotilesSGB63 0
#define IntrotilesSGB64 0
#define IntrotilesSGB65 0
#define IntrotilesSGB66 0
#define IntrotilesSGB67 0
#define IntrotilesSGB68 0
#define IntrotilesSGB69 0

/* CGB palette entries. */
#define IntrotilesCGB0 0
#define IntrotilesCGB1 0
#define IntrotilesCGB2 0
#define IntrotilesCGB3 0
#define IntrotilesCGB4 0
#define IntrotilesCGB5 0
#define IntrotilesCGB6 0
#define IntrotilesCGB7 0
#define IntrotilesCGB8 0
#define IntrotilesCGB9 0
#define IntrotilesCGB10 0
#define IntrotilesCGB11 0
#define IntrotilesCGB12 0
#define IntrotilesCGB13 0
#define IntrotilesCGB14 0
#define IntrotilesCGB15 0
#define IntrotilesCGB16 0
#define IntrotilesCGB17 0
#define IntrotilesCGB18 0
#define IntrotilesCGB19 0
#define IntrotilesCGB20 0
#define IntrotilesCGB21 0
#define IntrotilesCGB22 0
#define IntrotilesCGB23 0
#define IntrotilesCGB24 0
#define IntrotilesCGB25 0
#define IntrotilesCGB26 0
#define IntrotilesCGB27 0
#define IntrotilesCGB28 0
#define IntrotilesCGB29 0
#define IntrotilesCGB30 0
#define IntrotilesCGB31 0
#define IntrotilesCGB32 0
#define IntrotilesCGB33 0
#define IntrotilesCGB34 0
#define IntrotilesCGB35 0
#define IntrotilesCGB36 0
#define IntrotilesCGB37 0
#define IntrotilesCGB38 0
#define IntrotilesCGB39 0
#define IntrotilesCGB40 0
#define IntrotilesCGB41 0
#define IntrotilesCGB42 0
#define IntrotilesCGB43 0
#define IntrotilesCGB44 0
#define IntrotilesCGB45 0
#define IntrotilesCGB46 0
#define IntrotilesCGB47 0
#define IntrotilesCGB48 0
#define IntrotilesCGB49 0
#define IntrotilesCGB50 0
#define IntrotilesCGB51 0
#define IntrotilesCGB52 0
#define IntrotilesCGB53 0
#define IntrotilesCGB54 0
#define IntrotilesCGB55 0
#define IntrotilesCGB56 0
#define IntrotilesCGB57 0
#define IntrotilesCGB58 0
#define IntrotilesCGB59 0
#define IntrotilesCGB60 0
#define IntrotilesCGB61 0
#define IntrotilesCGB62 0
#define IntrotilesCGB63 0
#define IntrotilesCGB64 0
#define IntrotilesCGB65 0
#define IntrotilesCGB66 0
#define IntrotilesCGB67 0
#define IntrotilesCGB68 0
#define IntrotilesCGB69 0
/* Start of tile array. */
extern const unsigned char Introtiles[];

#endif

/* End of INTROFIELD.H */
