/*

 INTRODUCTIONTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 27

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __introductiontiles_h_INCLUDE
#define __introductiontiles_h_INCLUDE

/* Bank of tiles. */
#define shallweplayBank 0

/* Super Gameboy palette 0 */
#define shallweplaySGBPal0c0 32767
#define shallweplaySGBPal0c1 287
#define shallweplaySGBPal0c2 152
#define shallweplaySGBPal0c3 0

/* Super Gameboy palette 1 */
#define shallweplaySGBPal1c0 32767
#define shallweplaySGBPal1c1 8935
#define shallweplaySGBPal1c2 6596
#define shallweplaySGBPal1c3 5344

/* Super Gameboy palette 2 */
#define shallweplaySGBPal2c0 32767
#define shallweplaySGBPal2c1 8935
#define shallweplaySGBPal2c2 6596
#define shallweplaySGBPal2c3 5344

/* Super Gameboy palette 3 */
#define shallweplaySGBPal3c0 32767
#define shallweplaySGBPal3c1 8935
#define shallweplaySGBPal3c2 6596
#define shallweplaySGBPal3c3 5344

/* Gameboy Color palette 0 */
#define shallweplayCGBPal0c0 6076
#define shallweplayCGBPal0c1 8935
#define shallweplayCGBPal0c2 6596
#define shallweplayCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define shallweplayCGBPal1c0 6076
#define shallweplayCGBPal1c1 8935
#define shallweplayCGBPal1c2 6596
#define shallweplayCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define shallweplayCGBPal2c0 6076
#define shallweplayCGBPal2c1 8935
#define shallweplayCGBPal2c2 6596
#define shallweplayCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define shallweplayCGBPal3c0 6076
#define shallweplayCGBPal3c1 8935
#define shallweplayCGBPal3c2 6596
#define shallweplayCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define shallweplayCGBPal4c0 6076
#define shallweplayCGBPal4c1 8935
#define shallweplayCGBPal4c2 6596
#define shallweplayCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define shallweplayCGBPal5c0 6076
#define shallweplayCGBPal5c1 8935
#define shallweplayCGBPal5c2 6596
#define shallweplayCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define shallweplayCGBPal6c0 6076
#define shallweplayCGBPal6c1 8935
#define shallweplayCGBPal6c2 6596
#define shallweplayCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define shallweplayCGBPal7c0 6076
#define shallweplayCGBPal7c1 8935
#define shallweplayCGBPal7c2 6596
#define shallweplayCGBPal7c3 5344

/* SGB palette entries. */
#define shallweplaySGB0 0
#define shallweplaySGB1 0
#define shallweplaySGB2 0
#define shallweplaySGB3 0
#define shallweplaySGB4 0
#define shallweplaySGB5 0
#define shallweplaySGB6 0
#define shallweplaySGB7 0
#define shallweplaySGB8 0
#define shallweplaySGB9 0
#define shallweplaySGB10 0
#define shallweplaySGB11 0
#define shallweplaySGB12 0
#define shallweplaySGB13 0
#define shallweplaySGB14 0
#define shallweplaySGB15 0
#define shallweplaySGB16 0
#define shallweplaySGB17 0
#define shallweplaySGB18 0
#define shallweplaySGB19 0
#define shallweplaySGB20 0
#define shallweplaySGB21 0
#define shallweplaySGB22 0
#define shallweplaySGB23 0
#define shallweplaySGB24 0
#define shallweplaySGB25 0
#define shallweplaySGB26 0
#define shallweplaySGB27 0
/* Start of tile array. */
extern const unsigned char shallweplay[];

#endif

/* End of INTRODUCTIONTILES.H */
