/*

 KITSUNE4.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 15

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __kitsune4_h_INCLUDE
#define __kitsune4_h_INCLUDE

/* Bank of tiles. */
#define kitsunethink2Bank 0

/* Super Gameboy palette 0 */
#define kitsunethink2SGBPal0c0 32767
#define kitsunethink2SGBPal0c1 668
#define kitsunethink2SGBPal0c2 270
#define kitsunethink2SGBPal0c3 0

/* Super Gameboy palette 1 */
#define kitsunethink2SGBPal1c0 32767
#define kitsunethink2SGBPal1c1 8935
#define kitsunethink2SGBPal1c2 6596
#define kitsunethink2SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define kitsunethink2SGBPal2c0 32767
#define kitsunethink2SGBPal2c1 8935
#define kitsunethink2SGBPal2c2 6596
#define kitsunethink2SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define kitsunethink2SGBPal3c0 32767
#define kitsunethink2SGBPal3c1 8935
#define kitsunethink2SGBPal3c2 6596
#define kitsunethink2SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define kitsunethink2CGBPal0c0 6076
#define kitsunethink2CGBPal0c1 8935
#define kitsunethink2CGBPal0c2 6596
#define kitsunethink2CGBPal0c3 5344

/* Gameboy Color palette 1 */
#define kitsunethink2CGBPal1c0 6076
#define kitsunethink2CGBPal1c1 8935
#define kitsunethink2CGBPal1c2 6596
#define kitsunethink2CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define kitsunethink2CGBPal2c0 6076
#define kitsunethink2CGBPal2c1 8935
#define kitsunethink2CGBPal2c2 6596
#define kitsunethink2CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define kitsunethink2CGBPal3c0 6076
#define kitsunethink2CGBPal3c1 8935
#define kitsunethink2CGBPal3c2 6596
#define kitsunethink2CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define kitsunethink2CGBPal4c0 6076
#define kitsunethink2CGBPal4c1 8935
#define kitsunethink2CGBPal4c2 6596
#define kitsunethink2CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define kitsunethink2CGBPal5c0 6076
#define kitsunethink2CGBPal5c1 8935
#define kitsunethink2CGBPal5c2 6596
#define kitsunethink2CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define kitsunethink2CGBPal6c0 6076
#define kitsunethink2CGBPal6c1 8935
#define kitsunethink2CGBPal6c2 6596
#define kitsunethink2CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define kitsunethink2CGBPal7c0 6076
#define kitsunethink2CGBPal7c1 8935
#define kitsunethink2CGBPal7c2 6596
#define kitsunethink2CGBPal7c3 5344

/* SGB palette entries. */
#define kitsunethink2SGB0 0
#define kitsunethink2SGB1 0
#define kitsunethink2SGB2 0
#define kitsunethink2SGB3 0
#define kitsunethink2SGB4 0
#define kitsunethink2SGB5 0
#define kitsunethink2SGB6 0
#define kitsunethink2SGB7 0
#define kitsunethink2SGB8 0
#define kitsunethink2SGB9 0
#define kitsunethink2SGB10 0
#define kitsunethink2SGB11 0
#define kitsunethink2SGB12 0
#define kitsunethink2SGB13 0
#define kitsunethink2SGB14 0
#define kitsunethink2SGB15 0
/* Start of tile array. */
extern const unsigned char kitsunethink2[];

#endif

/* End of KITSUNE4.H */
