/*

 KITSUNE7.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 15

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __kitsune7_h_INCLUDE
#define __kitsune7_h_INCLUDE

/* Bank of tiles. */
#define kitsunesadBank 0

/* Super Gameboy palette 0 */
#define kitsunesadSGBPal0c0 32767
#define kitsunesadSGBPal0c1 668
#define kitsunesadSGBPal0c2 270
#define kitsunesadSGBPal0c3 0

/* Super Gameboy palette 1 */
#define kitsunesadSGBPal1c0 32767
#define kitsunesadSGBPal1c1 8935
#define kitsunesadSGBPal1c2 6596
#define kitsunesadSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define kitsunesadSGBPal2c0 32767
#define kitsunesadSGBPal2c1 8935
#define kitsunesadSGBPal2c2 6596
#define kitsunesadSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define kitsunesadSGBPal3c0 32767
#define kitsunesadSGBPal3c1 8935
#define kitsunesadSGBPal3c2 6596
#define kitsunesadSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define kitsunesadCGBPal0c0 6076
#define kitsunesadCGBPal0c1 8935
#define kitsunesadCGBPal0c2 6596
#define kitsunesadCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define kitsunesadCGBPal1c0 6076
#define kitsunesadCGBPal1c1 8935
#define kitsunesadCGBPal1c2 6596
#define kitsunesadCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define kitsunesadCGBPal2c0 6076
#define kitsunesadCGBPal2c1 8935
#define kitsunesadCGBPal2c2 6596
#define kitsunesadCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define kitsunesadCGBPal3c0 6076
#define kitsunesadCGBPal3c1 8935
#define kitsunesadCGBPal3c2 6596
#define kitsunesadCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define kitsunesadCGBPal4c0 6076
#define kitsunesadCGBPal4c1 8935
#define kitsunesadCGBPal4c2 6596
#define kitsunesadCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define kitsunesadCGBPal5c0 6076
#define kitsunesadCGBPal5c1 8935
#define kitsunesadCGBPal5c2 6596
#define kitsunesadCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define kitsunesadCGBPal6c0 6076
#define kitsunesadCGBPal6c1 8935
#define kitsunesadCGBPal6c2 6596
#define kitsunesadCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define kitsunesadCGBPal7c0 6076
#define kitsunesadCGBPal7c1 8935
#define kitsunesadCGBPal7c2 6596
#define kitsunesadCGBPal7c3 5344

/* SGB palette entries. */
#define kitsunesadSGB0 0
#define kitsunesadSGB1 0
#define kitsunesadSGB2 0
#define kitsunesadSGB3 0
#define kitsunesadSGB4 0
#define kitsunesadSGB5 0
#define kitsunesadSGB6 0
#define kitsunesadSGB7 0
#define kitsunesadSGB8 0
#define kitsunesadSGB9 0
#define kitsunesadSGB10 0
#define kitsunesadSGB11 0
#define kitsunesadSGB12 0
#define kitsunesadSGB13 0
#define kitsunesadSGB14 0
#define kitsunesadSGB15 0
/* Start of tile array. */
extern const unsigned char kitsunesad[];

#endif

/* End of KITSUNE7.H */
