/*

 KITSUNE1.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 15

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __kitsune1_h_INCLUDE
#define __kitsune1_h_INCLUDE

/* Bank of tiles. */
#define kitsuneloseBank 0

/* Super Gameboy palette 0 */
#define kitsuneloseSGBPal0c0 32767
#define kitsuneloseSGBPal0c1 668
#define kitsuneloseSGBPal0c2 270
#define kitsuneloseSGBPal0c3 0

/* Super Gameboy palette 1 */
#define kitsuneloseSGBPal1c0 32767
#define kitsuneloseSGBPal1c1 8935
#define kitsuneloseSGBPal1c2 6596
#define kitsuneloseSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define kitsuneloseSGBPal2c0 32767
#define kitsuneloseSGBPal2c1 8935
#define kitsuneloseSGBPal2c2 6596
#define kitsuneloseSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define kitsuneloseSGBPal3c0 32767
#define kitsuneloseSGBPal3c1 8935
#define kitsuneloseSGBPal3c2 6596
#define kitsuneloseSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define kitsuneloseCGBPal0c0 6076
#define kitsuneloseCGBPal0c1 8935
#define kitsuneloseCGBPal0c2 6596
#define kitsuneloseCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define kitsuneloseCGBPal1c0 6076
#define kitsuneloseCGBPal1c1 8935
#define kitsuneloseCGBPal1c2 6596
#define kitsuneloseCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define kitsuneloseCGBPal2c0 6076
#define kitsuneloseCGBPal2c1 8935
#define kitsuneloseCGBPal2c2 6596
#define kitsuneloseCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define kitsuneloseCGBPal3c0 6076
#define kitsuneloseCGBPal3c1 8935
#define kitsuneloseCGBPal3c2 6596
#define kitsuneloseCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define kitsuneloseCGBPal4c0 6076
#define kitsuneloseCGBPal4c1 8935
#define kitsuneloseCGBPal4c2 6596
#define kitsuneloseCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define kitsuneloseCGBPal5c0 6076
#define kitsuneloseCGBPal5c1 8935
#define kitsuneloseCGBPal5c2 6596
#define kitsuneloseCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define kitsuneloseCGBPal6c0 6076
#define kitsuneloseCGBPal6c1 8935
#define kitsuneloseCGBPal6c2 6596
#define kitsuneloseCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define kitsuneloseCGBPal7c0 6076
#define kitsuneloseCGBPal7c1 8935
#define kitsuneloseCGBPal7c2 6596
#define kitsuneloseCGBPal7c3 5344

/* SGB palette entries. */
#define kitsuneloseSGB0 0
#define kitsuneloseSGB1 0
#define kitsuneloseSGB2 0
#define kitsuneloseSGB3 0
#define kitsuneloseSGB4 0
#define kitsuneloseSGB5 0
#define kitsuneloseSGB6 0
#define kitsuneloseSGB7 0
#define kitsuneloseSGB8 0
#define kitsuneloseSGB9 0
#define kitsuneloseSGB10 0
#define kitsuneloseSGB11 0
#define kitsuneloseSGB12 0
#define kitsuneloseSGB13 0
#define kitsuneloseSGB14 0
#define kitsuneloseSGB15 0
/* Start of tile array. */
extern const unsigned char kitsunelose[];

#endif

/* End of KITSUNE1.H */
