/*

 KITSUNE5.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 15

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __kitsune5_h_INCLUDE
#define __kitsune5_h_INCLUDE

/* Bank of tiles. */
#define kitsunewin1Bank 0

/* Super Gameboy palette 0 */
#define kitsunewin1SGBPal0c0 32767
#define kitsunewin1SGBPal0c1 668
#define kitsunewin1SGBPal0c2 270
#define kitsunewin1SGBPal0c3 0

/* Super Gameboy palette 1 */
#define kitsunewin1SGBPal1c0 32767
#define kitsunewin1SGBPal1c1 8935
#define kitsunewin1SGBPal1c2 6596
#define kitsunewin1SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define kitsunewin1SGBPal2c0 32767
#define kitsunewin1SGBPal2c1 8935
#define kitsunewin1SGBPal2c2 6596
#define kitsunewin1SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define kitsunewin1SGBPal3c0 32767
#define kitsunewin1SGBPal3c1 8935
#define kitsunewin1SGBPal3c2 6596
#define kitsunewin1SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define kitsunewin1CGBPal0c0 6076
#define kitsunewin1CGBPal0c1 8935
#define kitsunewin1CGBPal0c2 6596
#define kitsunewin1CGBPal0c3 5344

/* Gameboy Color palette 1 */
#define kitsunewin1CGBPal1c0 6076
#define kitsunewin1CGBPal1c1 8935
#define kitsunewin1CGBPal1c2 6596
#define kitsunewin1CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define kitsunewin1CGBPal2c0 6076
#define kitsunewin1CGBPal2c1 8935
#define kitsunewin1CGBPal2c2 6596
#define kitsunewin1CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define kitsunewin1CGBPal3c0 6076
#define kitsunewin1CGBPal3c1 8935
#define kitsunewin1CGBPal3c2 6596
#define kitsunewin1CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define kitsunewin1CGBPal4c0 6076
#define kitsunewin1CGBPal4c1 8935
#define kitsunewin1CGBPal4c2 6596
#define kitsunewin1CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define kitsunewin1CGBPal5c0 6076
#define kitsunewin1CGBPal5c1 8935
#define kitsunewin1CGBPal5c2 6596
#define kitsunewin1CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define kitsunewin1CGBPal6c0 6076
#define kitsunewin1CGBPal6c1 8935
#define kitsunewin1CGBPal6c2 6596
#define kitsunewin1CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define kitsunewin1CGBPal7c0 6076
#define kitsunewin1CGBPal7c1 8935
#define kitsunewin1CGBPal7c2 6596
#define kitsunewin1CGBPal7c3 5344

/* SGB palette entries. */
#define kitsunewin1SGB0 0
#define kitsunewin1SGB1 0
#define kitsunewin1SGB2 0
#define kitsunewin1SGB3 0
#define kitsunewin1SGB4 0
#define kitsunewin1SGB5 0
#define kitsunewin1SGB6 0
#define kitsunewin1SGB7 0
#define kitsunewin1SGB8 0
#define kitsunewin1SGB9 0
#define kitsunewin1SGB10 0
#define kitsunewin1SGB11 0
#define kitsunewin1SGB12 0
#define kitsunewin1SGB13 0
#define kitsunewin1SGB14 0
#define kitsunewin1SGB15 0
/* Start of tile array. */
extern const unsigned char kitsunewin1[];

#endif

/* End of KITSUNE5.H */
