/*

 KITSUNE2.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 15

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __kitsune2_h_INCLUDE
#define __kitsune2_h_INCLUDE

/* Bank of tiles. */
#define kitsunehappyBank 0

/* Super Gameboy palette 0 */
#define kitsunehappySGBPal0c0 32767
#define kitsunehappySGBPal0c1 668
#define kitsunehappySGBPal0c2 270
#define kitsunehappySGBPal0c3 0

/* Super Gameboy palette 1 */
#define kitsunehappySGBPal1c0 32767
#define kitsunehappySGBPal1c1 8935
#define kitsunehappySGBPal1c2 6596
#define kitsunehappySGBPal1c3 5344

/* Super Gameboy palette 2 */
#define kitsunehappySGBPal2c0 32767
#define kitsunehappySGBPal2c1 8935
#define kitsunehappySGBPal2c2 6596
#define kitsunehappySGBPal2c3 5344

/* Super Gameboy palette 3 */
#define kitsunehappySGBPal3c0 32767
#define kitsunehappySGBPal3c1 8935
#define kitsunehappySGBPal3c2 6596
#define kitsunehappySGBPal3c3 5344

/* Gameboy Color palette 0 */
#define kitsunehappyCGBPal0c0 6076
#define kitsunehappyCGBPal0c1 8935
#define kitsunehappyCGBPal0c2 6596
#define kitsunehappyCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define kitsunehappyCGBPal1c0 6076
#define kitsunehappyCGBPal1c1 8935
#define kitsunehappyCGBPal1c2 6596
#define kitsunehappyCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define kitsunehappyCGBPal2c0 6076
#define kitsunehappyCGBPal2c1 8935
#define kitsunehappyCGBPal2c2 6596
#define kitsunehappyCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define kitsunehappyCGBPal3c0 6076
#define kitsunehappyCGBPal3c1 8935
#define kitsunehappyCGBPal3c2 6596
#define kitsunehappyCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define kitsunehappyCGBPal4c0 6076
#define kitsunehappyCGBPal4c1 8935
#define kitsunehappyCGBPal4c2 6596
#define kitsunehappyCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define kitsunehappyCGBPal5c0 6076
#define kitsunehappyCGBPal5c1 8935
#define kitsunehappyCGBPal5c2 6596
#define kitsunehappyCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define kitsunehappyCGBPal6c0 6076
#define kitsunehappyCGBPal6c1 8935
#define kitsunehappyCGBPal6c2 6596
#define kitsunehappyCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define kitsunehappyCGBPal7c0 6076
#define kitsunehappyCGBPal7c1 8935
#define kitsunehappyCGBPal7c2 6596
#define kitsunehappyCGBPal7c3 5344

/* SGB palette entries. */
#define kitsunehappySGB0 0
#define kitsunehappySGB1 0
#define kitsunehappySGB2 0
#define kitsunehappySGB3 0
#define kitsunehappySGB4 0
#define kitsunehappySGB5 0
#define kitsunehappySGB6 0
#define kitsunehappySGB7 0
#define kitsunehappySGB8 0
#define kitsunehappySGB9 0
#define kitsunehappySGB10 0
#define kitsunehappySGB11 0
#define kitsunehappySGB12 0
#define kitsunehappySGB13 0
#define kitsunehappySGB14 0
#define kitsunehappySGB15 0
/* Start of tile array. */
extern const unsigned char kitsunehappy[];

#endif

/* End of KITSUNE2.H */
