/*

 KITSUNE8.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 15

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __kitsune8_h_INCLUDE
#define __kitsune8_h_INCLUDE

/* Bank of tiles. */
#define kitsunenormalBank 0

/* Super Gameboy palette 0 */
#define kitsunenormalSGBPal0c0 32767
#define kitsunenormalSGBPal0c1 668
#define kitsunenormalSGBPal0c2 270
#define kitsunenormalSGBPal0c3 0

/* Super Gameboy palette 1 */
#define kitsunenormalSGBPal1c0 32767
#define kitsunenormalSGBPal1c1 8935
#define kitsunenormalSGBPal1c2 6596
#define kitsunenormalSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define kitsunenormalSGBPal2c0 32767
#define kitsunenormalSGBPal2c1 8935
#define kitsunenormalSGBPal2c2 6596
#define kitsunenormalSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define kitsunenormalSGBPal3c0 32767
#define kitsunenormalSGBPal3c1 8935
#define kitsunenormalSGBPal3c2 6596
#define kitsunenormalSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define kitsunenormalCGBPal0c0 6076
#define kitsunenormalCGBPal0c1 8935
#define kitsunenormalCGBPal0c2 6596
#define kitsunenormalCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define kitsunenormalCGBPal1c0 6076
#define kitsunenormalCGBPal1c1 8935
#define kitsunenormalCGBPal1c2 6596
#define kitsunenormalCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define kitsunenormalCGBPal2c0 6076
#define kitsunenormalCGBPal2c1 8935
#define kitsunenormalCGBPal2c2 6596
#define kitsunenormalCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define kitsunenormalCGBPal3c0 6076
#define kitsunenormalCGBPal3c1 8935
#define kitsunenormalCGBPal3c2 6596
#define kitsunenormalCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define kitsunenormalCGBPal4c0 6076
#define kitsunenormalCGBPal4c1 8935
#define kitsunenormalCGBPal4c2 6596
#define kitsunenormalCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define kitsunenormalCGBPal5c0 6076
#define kitsunenormalCGBPal5c1 8935
#define kitsunenormalCGBPal5c2 6596
#define kitsunenormalCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define kitsunenormalCGBPal6c0 6076
#define kitsunenormalCGBPal6c1 8935
#define kitsunenormalCGBPal6c2 6596
#define kitsunenormalCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define kitsunenormalCGBPal7c0 6076
#define kitsunenormalCGBPal7c1 8935
#define kitsunenormalCGBPal7c2 6596
#define kitsunenormalCGBPal7c3 5344

/* SGB palette entries. */
#define kitsunenormalSGB0 0
#define kitsunenormalSGB1 0
#define kitsunenormalSGB2 0
#define kitsunenormalSGB3 0
#define kitsunenormalSGB4 0
#define kitsunenormalSGB5 0
#define kitsunenormalSGB6 0
#define kitsunenormalSGB7 0
#define kitsunenormalSGB8 0
#define kitsunenormalSGB9 0
#define kitsunenormalSGB10 0
#define kitsunenormalSGB11 0
#define kitsunenormalSGB12 0
#define kitsunenormalSGB13 0
#define kitsunenormalSGB14 0
#define kitsunenormalSGB15 0
/* Start of tile array. */
extern const unsigned char kitsunenormal[];

#endif

/* End of KITSUNE8.H */
