/*

 NINJA.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 13

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __ninja_h_INCLUDE
#define __ninja_h_INCLUDE

/* Bank of tiles. */
#define shinobiBank 0

/* Super Gameboy palette 0 */
#define shinobiSGBPal0c0 32767
#define shinobiSGBPal0c1 15230
#define shinobiSGBPal0c2 16705
#define shinobiSGBPal0c3 0

/* Super Gameboy palette 1 */
#define shinobiSGBPal1c0 32767
#define shinobiSGBPal1c1 8935
#define shinobiSGBPal1c2 6596
#define shinobiSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define shinobiSGBPal2c0 32767
#define shinobiSGBPal2c1 8935
#define shinobiSGBPal2c2 6596
#define shinobiSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define shinobiSGBPal3c0 32767
#define shinobiSGBPal3c1 8935
#define shinobiSGBPal3c2 6596
#define shinobiSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define shinobiCGBPal0c0 6076
#define shinobiCGBPal0c1 8935
#define shinobiCGBPal0c2 6596
#define shinobiCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define shinobiCGBPal1c0 6076
#define shinobiCGBPal1c1 8935
#define shinobiCGBPal1c2 6596
#define shinobiCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define shinobiCGBPal2c0 6076
#define shinobiCGBPal2c1 8935
#define shinobiCGBPal2c2 6596
#define shinobiCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define shinobiCGBPal3c0 6076
#define shinobiCGBPal3c1 8935
#define shinobiCGBPal3c2 6596
#define shinobiCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define shinobiCGBPal4c0 6076
#define shinobiCGBPal4c1 8935
#define shinobiCGBPal4c2 6596
#define shinobiCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define shinobiCGBPal5c0 6076
#define shinobiCGBPal5c1 8935
#define shinobiCGBPal5c2 6596
#define shinobiCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define shinobiCGBPal6c0 6076
#define shinobiCGBPal6c1 8935
#define shinobiCGBPal6c2 6596
#define shinobiCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define shinobiCGBPal7c0 6076
#define shinobiCGBPal7c1 8935
#define shinobiCGBPal7c2 6596
#define shinobiCGBPal7c3 5344

/* SGB palette entries. */
#define shinobiSGB0 0
#define shinobiSGB1 0
#define shinobiSGB2 0
#define shinobiSGB3 0
#define shinobiSGB4 0
#define shinobiSGB5 0
#define shinobiSGB6 0
#define shinobiSGB7 0
#define shinobiSGB8 0
#define shinobiSGB9 0
#define shinobiSGB10 0
#define shinobiSGB11 0
#define shinobiSGB12 0
#define shinobiSGB13 0
/* Start of tile array. */
extern const unsigned char shinobi[];

#endif

/* End of NINJA.H */
