/*

 OOTE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 25

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __oote_h_INCLUDE
#define __oote_h_INCLUDE

/* Bank of tiles. */
#define checktilesBank 0

/* Super Gameboy palette 0 */
#define checktilesSGBPal0c0 32767
#define checktilesSGBPal0c1 31
#define checktilesSGBPal0c2 20
#define checktilesSGBPal0c3 0

/* Super Gameboy palette 1 */
#define checktilesSGBPal1c0 32767
#define checktilesSGBPal1c1 8935
#define checktilesSGBPal1c2 6596
#define checktilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define checktilesSGBPal2c0 32767
#define checktilesSGBPal2c1 8935
#define checktilesSGBPal2c2 6596
#define checktilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define checktilesSGBPal3c0 32767
#define checktilesSGBPal3c1 8935
#define checktilesSGBPal3c2 6596
#define checktilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define checktilesCGBPal0c0 6076
#define checktilesCGBPal0c1 8935
#define checktilesCGBPal0c2 6596
#define checktilesCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define checktilesCGBPal1c0 6076
#define checktilesCGBPal1c1 8935
#define checktilesCGBPal1c2 6596
#define checktilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define checktilesCGBPal2c0 6076
#define checktilesCGBPal2c1 8935
#define checktilesCGBPal2c2 6596
#define checktilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define checktilesCGBPal3c0 6076
#define checktilesCGBPal3c1 8935
#define checktilesCGBPal3c2 6596
#define checktilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define checktilesCGBPal4c0 6076
#define checktilesCGBPal4c1 8935
#define checktilesCGBPal4c2 6596
#define checktilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define checktilesCGBPal5c0 6076
#define checktilesCGBPal5c1 8935
#define checktilesCGBPal5c2 6596
#define checktilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define checktilesCGBPal6c0 6076
#define checktilesCGBPal6c1 8935
#define checktilesCGBPal6c2 6596
#define checktilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define checktilesCGBPal7c0 6076
#define checktilesCGBPal7c1 8935
#define checktilesCGBPal7c2 6596
#define checktilesCGBPal7c3 5344

/* SGB palette entries. */
#define checktilesSGB0 0
#define checktilesSGB1 0
#define checktilesSGB2 0
#define checktilesSGB3 0
#define checktilesSGB4 0
#define checktilesSGB5 0
#define checktilesSGB6 0
#define checktilesSGB7 0
#define checktilesSGB8 0
#define checktilesSGB9 0
#define checktilesSGB10 0
#define checktilesSGB11 0
#define checktilesSGB12 0
#define checktilesSGB13 0
#define checktilesSGB14 0
#define checktilesSGB15 0
#define checktilesSGB16 0
#define checktilesSGB17 0
#define checktilesSGB18 0
#define checktilesSGB19 0
#define checktilesSGB20 0
#define checktilesSGB21 0
#define checktilesSGB22 0
#define checktilesSGB23 0
#define checktilesSGB24 0
#define checktilesSGB25 0
/* Start of tile array. */
extern const unsigned char checktiles[];

#endif

/* End of OOTE.H */
