/*

 OPENINGTILES1.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 38

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __openingtiles1_h_INCLUDE
#define __openingtiles1_h_INCLUDE

/* Bank of tiles. */
#define opentiles1Bank 0

/* Super Gameboy palette 0 */
#define opentiles1SGBPal0c0 32767
#define opentiles1SGBPal0c1 32264
#define opentiles1SGBPal0c2 32532
#define opentiles1SGBPal0c3 0

/* Super Gameboy palette 1 */
#define opentiles1SGBPal1c0 32767
#define opentiles1SGBPal1c1 8935
#define opentiles1SGBPal1c2 6596
#define opentiles1SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define opentiles1SGBPal2c0 32767
#define opentiles1SGBPal2c1 8935
#define opentiles1SGBPal2c2 6596
#define opentiles1SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define opentiles1SGBPal3c0 32767
#define opentiles1SGBPal3c1 8935
#define opentiles1SGBPal3c2 6596
#define opentiles1SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define opentiles1CGBPal0c0 6076
#define opentiles1CGBPal0c1 8935
#define opentiles1CGBPal0c2 6596
#define opentiles1CGBPal0c3 5344

/* Gameboy Color palette 1 */
#define opentiles1CGBPal1c0 6076
#define opentiles1CGBPal1c1 8935
#define opentiles1CGBPal1c2 6596
#define opentiles1CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define opentiles1CGBPal2c0 6076
#define opentiles1CGBPal2c1 8935
#define opentiles1CGBPal2c2 6596
#define opentiles1CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define opentiles1CGBPal3c0 6076
#define opentiles1CGBPal3c1 8935
#define opentiles1CGBPal3c2 6596
#define opentiles1CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define opentiles1CGBPal4c0 6076
#define opentiles1CGBPal4c1 8935
#define opentiles1CGBPal4c2 6596
#define opentiles1CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define opentiles1CGBPal5c0 6076
#define opentiles1CGBPal5c1 8935
#define opentiles1CGBPal5c2 6596
#define opentiles1CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define opentiles1CGBPal6c0 6076
#define opentiles1CGBPal6c1 8935
#define opentiles1CGBPal6c2 6596
#define opentiles1CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define opentiles1CGBPal7c0 6076
#define opentiles1CGBPal7c1 8935
#define opentiles1CGBPal7c2 6596
#define opentiles1CGBPal7c3 5344

/* SGB palette entries. */
#define opentiles1SGB0 0
#define opentiles1SGB1 0
#define opentiles1SGB2 0
#define opentiles1SGB3 0
#define opentiles1SGB4 0
#define opentiles1SGB5 0
#define opentiles1SGB6 0
#define opentiles1SGB7 0
#define opentiles1SGB8 0
#define opentiles1SGB9 0
#define opentiles1SGB10 0
#define opentiles1SGB11 0
#define opentiles1SGB12 0
#define opentiles1SGB13 0
#define opentiles1SGB14 0
#define opentiles1SGB15 0
#define opentiles1SGB16 0
#define opentiles1SGB17 0
#define opentiles1SGB18 0
#define opentiles1SGB19 0
#define opentiles1SGB20 0
#define opentiles1SGB21 0
#define opentiles1SGB22 0
#define opentiles1SGB23 0
#define opentiles1SGB24 0
#define opentiles1SGB25 0
#define opentiles1SGB26 0
#define opentiles1SGB27 0
#define opentiles1SGB28 0
#define opentiles1SGB29 0
#define opentiles1SGB30 0
#define opentiles1SGB31 0
#define opentiles1SGB32 0
#define opentiles1SGB33 0
#define opentiles1SGB34 0
#define opentiles1SGB35 0
#define opentiles1SGB36 0
#define opentiles1SGB37 0
#define opentiles1SGB38 0
/* Start of tile array. */
extern const unsigned char opentiles1[];

#endif

/* End of OPENINGTILES1.H */
