/*

 OPENINGTILES2.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 69

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __openingtiles2_h_INCLUDE
#define __openingtiles2_h_INCLUDE

/* Bank of tiles. */
#define opentiles2Bank 0

/* Super Gameboy palette 0 */
#define opentiles2SGBPal0c0 32767
#define opentiles2SGBPal0c1 15230
#define opentiles2SGBPal0c2 16705
#define opentiles2SGBPal0c3 0

/* Super Gameboy palette 1 */
#define opentiles2SGBPal1c0 32767
#define opentiles2SGBPal1c1 8935
#define opentiles2SGBPal1c2 6596
#define opentiles2SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define opentiles2SGBPal2c0 32767
#define opentiles2SGBPal2c1 8935
#define opentiles2SGBPal2c2 6596
#define opentiles2SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define opentiles2SGBPal3c0 32767
#define opentiles2SGBPal3c1 8935
#define opentiles2SGBPal3c2 6596
#define opentiles2SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define opentiles2CGBPal0c0 6076
#define opentiles2CGBPal0c1 8935
#define opentiles2CGBPal0c2 6596
#define opentiles2CGBPal0c3 5344

/* Gameboy Color palette 1 */
#define opentiles2CGBPal1c0 6076
#define opentiles2CGBPal1c1 8935
#define opentiles2CGBPal1c2 6596
#define opentiles2CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define opentiles2CGBPal2c0 6076
#define opentiles2CGBPal2c1 8935
#define opentiles2CGBPal2c2 6596
#define opentiles2CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define opentiles2CGBPal3c0 6076
#define opentiles2CGBPal3c1 8935
#define opentiles2CGBPal3c2 6596
#define opentiles2CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define opentiles2CGBPal4c0 6076
#define opentiles2CGBPal4c1 8935
#define opentiles2CGBPal4c2 6596
#define opentiles2CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define opentiles2CGBPal5c0 6076
#define opentiles2CGBPal5c1 8935
#define opentiles2CGBPal5c2 6596
#define opentiles2CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define opentiles2CGBPal6c0 6076
#define opentiles2CGBPal6c1 8935
#define opentiles2CGBPal6c2 6596
#define opentiles2CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define opentiles2CGBPal7c0 6076
#define opentiles2CGBPal7c1 8935
#define opentiles2CGBPal7c2 6596
#define opentiles2CGBPal7c3 5344

/* SGB palette entries. */
#define opentiles2SGB0 0
#define opentiles2SGB1 0
#define opentiles2SGB2 0
#define opentiles2SGB3 0
#define opentiles2SGB4 0
#define opentiles2SGB5 0
#define opentiles2SGB6 0
#define opentiles2SGB7 0
#define opentiles2SGB8 0
#define opentiles2SGB9 0
#define opentiles2SGB10 0
#define opentiles2SGB11 0
#define opentiles2SGB12 0
#define opentiles2SGB13 0
#define opentiles2SGB14 0
#define opentiles2SGB15 0
#define opentiles2SGB16 0
#define opentiles2SGB17 0
#define opentiles2SGB18 0
#define opentiles2SGB19 0
#define opentiles2SGB20 0
#define opentiles2SGB21 0
#define opentiles2SGB22 0
#define opentiles2SGB23 0
#define opentiles2SGB24 0
#define opentiles2SGB25 0
#define opentiles2SGB26 0
#define opentiles2SGB27 0
#define opentiles2SGB28 0
#define opentiles2SGB29 0
#define opentiles2SGB30 0
#define opentiles2SGB31 0
#define opentiles2SGB32 0
#define opentiles2SGB33 0
#define opentiles2SGB34 0
#define opentiles2SGB35 0
#define opentiles2SGB36 0
#define opentiles2SGB37 0
#define opentiles2SGB38 0
#define opentiles2SGB39 0
#define opentiles2SGB40 0
#define opentiles2SGB41 0
#define opentiles2SGB42 0
#define opentiles2SGB43 0
#define opentiles2SGB44 0
#define opentiles2SGB45 0
#define opentiles2SGB46 0
#define opentiles2SGB47 0
#define opentiles2SGB48 0
#define opentiles2SGB49 0
#define opentiles2SGB50 0
#define opentiles2SGB51 0
#define opentiles2SGB52 0
#define opentiles2SGB53 0
#define opentiles2SGB54 0
#define opentiles2SGB55 0
#define opentiles2SGB56 0
#define opentiles2SGB57 0
#define opentiles2SGB58 0
#define opentiles2SGB59 0
#define opentiles2SGB60 0
#define opentiles2SGB61 0
#define opentiles2SGB62 0
#define opentiles2SGB63 0
#define opentiles2SGB64 0
#define opentiles2SGB65 0
#define opentiles2SGB66 0
#define opentiles2SGB67 0
#define opentiles2SGB68 0
#define opentiles2SGB69 0
/* Start of tile array. */
extern const unsigned char opentiles2[];

#endif

/* End of OPENINGTILES2.H */
