/*

 OPTIONSCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 3
   Map size      : 20 x 18
   Tile set      : Shogimenutiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __optionscreen_h_INCLUDE
#define __optionscreen_h_INCLUDE

#define menuscreenWidth 20
#define menuscreenHeight 18
#define menuscreenBank 3

#define menuscreen menuscreenPLN0
extern const unsigned char menuscreenPLN0[];

#endif

/* End of OPTIONSCREEN.H */
