/*

 OPTIONSCREEN3.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Shogimenutiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __optionscreen3_h_INCLUDE
#define __optionscreen3_h_INCLUDE

#define levelscreenWidth 20
#define levelscreenHeight 18
#define levelscreenBank 0

#define levelscreen levelscreenPLN0
extern const unsigned char levelscreenPLN0[];

#endif

/* End of OPTIONSCREEN3.H */
