/*

 OPTIONSCREEN2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Shogimenutiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __optionscreen2_h_INCLUDE
#define __optionscreen2_h_INCLUDE

#define colorscreenWidth 20
#define colorscreenHeight 18
#define colorscreenBank 0

#define colorscreen colorscreenPLN0
extern const unsigned char colorscreenPLN0[];

#endif

/* End of OPTIONSCREEN2.H */
