/*

 RACCOONSILVERSWORD.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 17

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __raccoonsilversword_h_INCLUDE
#define __raccoonsilversword_h_INCLUDE

/* Bank of tiles. */
#define kuroiginshouslashBank 0

/* Super Gameboy palette 0 */
#define kuroiginshouslashSGBPal0c0 32767
#define kuroiginshouslashSGBPal0c1 25368
#define kuroiginshouslashSGBPal0c2 12684
#define kuroiginshouslashSGBPal0c3 0

/* Super Gameboy palette 1 */
#define kuroiginshouslashSGBPal1c0 32767
#define kuroiginshouslashSGBPal1c1 8935
#define kuroiginshouslashSGBPal1c2 6596
#define kuroiginshouslashSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define kuroiginshouslashSGBPal2c0 32767
#define kuroiginshouslashSGBPal2c1 8935
#define kuroiginshouslashSGBPal2c2 6596
#define kuroiginshouslashSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define kuroiginshouslashSGBPal3c0 32767
#define kuroiginshouslashSGBPal3c1 8935
#define kuroiginshouslashSGBPal3c2 6596
#define kuroiginshouslashSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define kuroiginshouslashCGBPal0c0 6076
#define kuroiginshouslashCGBPal0c1 8935
#define kuroiginshouslashCGBPal0c2 6596
#define kuroiginshouslashCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define kuroiginshouslashCGBPal1c0 6076
#define kuroiginshouslashCGBPal1c1 8935
#define kuroiginshouslashCGBPal1c2 6596
#define kuroiginshouslashCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define kuroiginshouslashCGBPal2c0 6076
#define kuroiginshouslashCGBPal2c1 8935
#define kuroiginshouslashCGBPal2c2 6596
#define kuroiginshouslashCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define kuroiginshouslashCGBPal3c0 6076
#define kuroiginshouslashCGBPal3c1 8935
#define kuroiginshouslashCGBPal3c2 6596
#define kuroiginshouslashCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define kuroiginshouslashCGBPal4c0 6076
#define kuroiginshouslashCGBPal4c1 8935
#define kuroiginshouslashCGBPal4c2 6596
#define kuroiginshouslashCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define kuroiginshouslashCGBPal5c0 6076
#define kuroiginshouslashCGBPal5c1 8935
#define kuroiginshouslashCGBPal5c2 6596
#define kuroiginshouslashCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define kuroiginshouslashCGBPal6c0 6076
#define kuroiginshouslashCGBPal6c1 8935
#define kuroiginshouslashCGBPal6c2 6596
#define kuroiginshouslashCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define kuroiginshouslashCGBPal7c0 6076
#define kuroiginshouslashCGBPal7c1 8935
#define kuroiginshouslashCGBPal7c2 6596
#define kuroiginshouslashCGBPal7c3 5344

/* SGB palette entries. */
#define kuroiginshouslashSGB0 0
#define kuroiginshouslashSGB1 0
#define kuroiginshouslashSGB2 0
#define kuroiginshouslashSGB3 0
#define kuroiginshouslashSGB4 0
#define kuroiginshouslashSGB5 0
#define kuroiginshouslashSGB6 0
#define kuroiginshouslashSGB7 0
#define kuroiginshouslashSGB8 0
#define kuroiginshouslashSGB9 0
#define kuroiginshouslashSGB10 0
#define kuroiginshouslashSGB11 0
#define kuroiginshouslashSGB12 0
#define kuroiginshouslashSGB13 0
#define kuroiginshouslashSGB14 0
#define kuroiginshouslashSGB15 0
#define kuroiginshouslashSGB16 0
#define kuroiginshouslashSGB17 0
/* Start of tile array. */
extern const unsigned char kuroiginshouslash[];

#endif

/* End of RACCOONSILVERSWORD.H */
