/*

 RACCOONPAWN1.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 13

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __raccoonpawn1_h_INCLUDE
#define __raccoonpawn1_h_INCLUDE

/* Bank of tiles. */
#define kuroifuhyo1Bank 0

/* Super Gameboy palette 0 */
#define kuroifuhyo1SGBPal0c0 32767
#define kuroifuhyo1SGBPal0c1 8728
#define kuroifuhyo1SGBPal0c2 140
#define kuroifuhyo1SGBPal0c3 0

/* Super Gameboy palette 1 */
#define kuroifuhyo1SGBPal1c0 32767
#define kuroifuhyo1SGBPal1c1 671
#define kuroifuhyo1SGBPal1c2 408
#define kuroifuhyo1SGBPal1c3 0

/* Super Gameboy palette 2 */
#define kuroifuhyo1SGBPal2c0 32767
#define kuroifuhyo1SGBPal2c1 8935
#define kuroifuhyo1SGBPal2c2 6596
#define kuroifuhyo1SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define kuroifuhyo1SGBPal3c0 32767
#define kuroifuhyo1SGBPal3c1 8935
#define kuroifuhyo1SGBPal3c2 6596
#define kuroifuhyo1SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define kuroifuhyo1CGBPal0c0 6076
#define kuroifuhyo1CGBPal0c1 8935
#define kuroifuhyo1CGBPal0c2 6596
#define kuroifuhyo1CGBPal0c3 5344

/* Gameboy Color palette 1 */
#define kuroifuhyo1CGBPal1c0 6076
#define kuroifuhyo1CGBPal1c1 8935
#define kuroifuhyo1CGBPal1c2 6596
#define kuroifuhyo1CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define kuroifuhyo1CGBPal2c0 6076
#define kuroifuhyo1CGBPal2c1 8935
#define kuroifuhyo1CGBPal2c2 6596
#define kuroifuhyo1CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define kuroifuhyo1CGBPal3c0 6076
#define kuroifuhyo1CGBPal3c1 8935
#define kuroifuhyo1CGBPal3c2 6596
#define kuroifuhyo1CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define kuroifuhyo1CGBPal4c0 6076
#define kuroifuhyo1CGBPal4c1 8935
#define kuroifuhyo1CGBPal4c2 6596
#define kuroifuhyo1CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define kuroifuhyo1CGBPal5c0 6076
#define kuroifuhyo1CGBPal5c1 8935
#define kuroifuhyo1CGBPal5c2 6596
#define kuroifuhyo1CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define kuroifuhyo1CGBPal6c0 6076
#define kuroifuhyo1CGBPal6c1 8935
#define kuroifuhyo1CGBPal6c2 6596
#define kuroifuhyo1CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define kuroifuhyo1CGBPal7c0 6076
#define kuroifuhyo1CGBPal7c1 8935
#define kuroifuhyo1CGBPal7c2 6596
#define kuroifuhyo1CGBPal7c3 5344

/* SGB palette entries. */
#define kuroifuhyo1SGB0 0
#define kuroifuhyo1SGB1 0
#define kuroifuhyo1SGB2 0
#define kuroifuhyo1SGB3 0
#define kuroifuhyo1SGB4 0
#define kuroifuhyo1SGB5 0
#define kuroifuhyo1SGB6 0
#define kuroifuhyo1SGB7 0
#define kuroifuhyo1SGB8 0
#define kuroifuhyo1SGB9 0
#define kuroifuhyo1SGB10 0
#define kuroifuhyo1SGB11 0
#define kuroifuhyo1SGB12 0
#define kuroifuhyo1SGB13 0
/* Start of tile array. */
extern const unsigned char kuroifuhyo1[];

#endif

/* End of RACCOONPAWN1.H */
