/*

 RACCOONBISHOP1.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 14

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __raccoonbishop1_h_INCLUDE
#define __raccoonbishop1_h_INCLUDE

/* Bank of tiles. */
#define kuroikakugyo1Bank 0

/* Super Gameboy palette 0 */
#define kuroikakugyo1SGBPal0c0 32767
#define kuroikakugyo1SGBPal0c1 8728
#define kuroikakugyo1SGBPal0c2 140
#define kuroikakugyo1SGBPal0c3 0

/* Super Gameboy palette 1 */
#define kuroikakugyo1SGBPal1c0 32767
#define kuroikakugyo1SGBPal1c1 671
#define kuroikakugyo1SGBPal1c2 408
#define kuroikakugyo1SGBPal1c3 0

/* Super Gameboy palette 2 */
#define kuroikakugyo1SGBPal2c0 32767
#define kuroikakugyo1SGBPal2c1 8935
#define kuroikakugyo1SGBPal2c2 6596
#define kuroikakugyo1SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define kuroikakugyo1SGBPal3c0 32767
#define kuroikakugyo1SGBPal3c1 8935
#define kuroikakugyo1SGBPal3c2 6596
#define kuroikakugyo1SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define kuroikakugyo1CGBPal0c0 6076
#define kuroikakugyo1CGBPal0c1 8935
#define kuroikakugyo1CGBPal0c2 6596
#define kuroikakugyo1CGBPal0c3 5344

/* Gameboy Color palette 1 */
#define kuroikakugyo1CGBPal1c0 6076
#define kuroikakugyo1CGBPal1c1 8935
#define kuroikakugyo1CGBPal1c2 6596
#define kuroikakugyo1CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define kuroikakugyo1CGBPal2c0 6076
#define kuroikakugyo1CGBPal2c1 8935
#define kuroikakugyo1CGBPal2c2 6596
#define kuroikakugyo1CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define kuroikakugyo1CGBPal3c0 6076
#define kuroikakugyo1CGBPal3c1 8935
#define kuroikakugyo1CGBPal3c2 6596
#define kuroikakugyo1CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define kuroikakugyo1CGBPal4c0 6076
#define kuroikakugyo1CGBPal4c1 8935
#define kuroikakugyo1CGBPal4c2 6596
#define kuroikakugyo1CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define kuroikakugyo1CGBPal5c0 6076
#define kuroikakugyo1CGBPal5c1 8935
#define kuroikakugyo1CGBPal5c2 6596
#define kuroikakugyo1CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define kuroikakugyo1CGBPal6c0 6076
#define kuroikakugyo1CGBPal6c1 8935
#define kuroikakugyo1CGBPal6c2 6596
#define kuroikakugyo1CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define kuroikakugyo1CGBPal7c0 6076
#define kuroikakugyo1CGBPal7c1 8935
#define kuroikakugyo1CGBPal7c2 6596
#define kuroikakugyo1CGBPal7c3 5344

/* SGB palette entries. */
#define kuroikakugyo1SGB0 0
#define kuroikakugyo1SGB1 0
#define kuroikakugyo1SGB2 0
#define kuroikakugyo1SGB3 0
#define kuroikakugyo1SGB4 0
#define kuroikakugyo1SGB5 0
#define kuroikakugyo1SGB6 0
#define kuroikakugyo1SGB7 0
#define kuroikakugyo1SGB8 0
#define kuroikakugyo1SGB9 0
#define kuroikakugyo1SGB10 0
#define kuroikakugyo1SGB11 0
#define kuroikakugyo1SGB12 0
#define kuroikakugyo1SGB13 0
#define kuroikakugyo1SGB14 0
/* Start of tile array. */
extern const unsigned char kuroikakugyo1[];

#endif

/* End of RACCOONBISHOP1.H */
