/*

 RACCOONGOLD1.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 14

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __raccoongold1_h_INCLUDE
#define __raccoongold1_h_INCLUDE

/* Bank of tiles. */
#define kuroikinshou1Bank 0

/* Super Gameboy palette 0 */
#define kuroikinshou1SGBPal0c0 32767
#define kuroikinshou1SGBPal0c1 8728
#define kuroikinshou1SGBPal0c2 140
#define kuroikinshou1SGBPal0c3 0

/* Super Gameboy palette 1 */
#define kuroikinshou1SGBPal1c0 32767
#define kuroikinshou1SGBPal1c1 671
#define kuroikinshou1SGBPal1c2 408
#define kuroikinshou1SGBPal1c3 0

/* Super Gameboy palette 2 */
#define kuroikinshou1SGBPal2c0 32767
#define kuroikinshou1SGBPal2c1 8935
#define kuroikinshou1SGBPal2c2 6596
#define kuroikinshou1SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define kuroikinshou1SGBPal3c0 32767
#define kuroikinshou1SGBPal3c1 8935
#define kuroikinshou1SGBPal3c2 6596
#define kuroikinshou1SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define kuroikinshou1CGBPal0c0 6076
#define kuroikinshou1CGBPal0c1 8935
#define kuroikinshou1CGBPal0c2 6596
#define kuroikinshou1CGBPal0c3 5344

/* Gameboy Color palette 1 */
#define kuroikinshou1CGBPal1c0 6076
#define kuroikinshou1CGBPal1c1 8935
#define kuroikinshou1CGBPal1c2 6596
#define kuroikinshou1CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define kuroikinshou1CGBPal2c0 6076
#define kuroikinshou1CGBPal2c1 8935
#define kuroikinshou1CGBPal2c2 6596
#define kuroikinshou1CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define kuroikinshou1CGBPal3c0 6076
#define kuroikinshou1CGBPal3c1 8935
#define kuroikinshou1CGBPal3c2 6596
#define kuroikinshou1CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define kuroikinshou1CGBPal4c0 6076
#define kuroikinshou1CGBPal4c1 8935
#define kuroikinshou1CGBPal4c2 6596
#define kuroikinshou1CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define kuroikinshou1CGBPal5c0 6076
#define kuroikinshou1CGBPal5c1 8935
#define kuroikinshou1CGBPal5c2 6596
#define kuroikinshou1CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define kuroikinshou1CGBPal6c0 6076
#define kuroikinshou1CGBPal6c1 8935
#define kuroikinshou1CGBPal6c2 6596
#define kuroikinshou1CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define kuroikinshou1CGBPal7c0 6076
#define kuroikinshou1CGBPal7c1 8935
#define kuroikinshou1CGBPal7c2 6596
#define kuroikinshou1CGBPal7c3 5344

/* SGB palette entries. */
#define kuroikinshou1SGB0 0
#define kuroikinshou1SGB1 0
#define kuroikinshou1SGB2 0
#define kuroikinshou1SGB3 0
#define kuroikinshou1SGB4 0
#define kuroikinshou1SGB5 0
#define kuroikinshou1SGB6 0
#define kuroikinshou1SGB7 0
#define kuroikinshou1SGB8 0
#define kuroikinshou1SGB9 0
#define kuroikinshou1SGB10 0
#define kuroikinshou1SGB11 0
#define kuroikinshou1SGB12 0
#define kuroikinshou1SGB13 0
#define kuroikinshou1SGB14 0
/* Start of tile array. */
extern const unsigned char kuroikinshou1[];

#endif

/* End of RACCOONGOLD1.H */
