/*

 RACCOONROOK2.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 14

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __raccoonrook2_h_INCLUDE
#define __raccoonrook2_h_INCLUDE

/* Bank of tiles. */
#define kuroihisha2Bank 0

/* Super Gameboy palette 0 */
#define kuroihisha2SGBPal0c0 32767
#define kuroihisha2SGBPal0c1 8728
#define kuroihisha2SGBPal0c2 140
#define kuroihisha2SGBPal0c3 0

/* Super Gameboy palette 1 */
#define kuroihisha2SGBPal1c0 32767
#define kuroihisha2SGBPal1c1 671
#define kuroihisha2SGBPal1c2 408
#define kuroihisha2SGBPal1c3 0

/* Super Gameboy palette 2 */
#define kuroihisha2SGBPal2c0 32767
#define kuroihisha2SGBPal2c1 8935
#define kuroihisha2SGBPal2c2 6596
#define kuroihisha2SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define kuroihisha2SGBPal3c0 32767
#define kuroihisha2SGBPal3c1 8935
#define kuroihisha2SGBPal3c2 6596
#define kuroihisha2SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define kuroihisha2CGBPal0c0 6076
#define kuroihisha2CGBPal0c1 8935
#define kuroihisha2CGBPal0c2 6596
#define kuroihisha2CGBPal0c3 5344

/* Gameboy Color palette 1 */
#define kuroihisha2CGBPal1c0 6076
#define kuroihisha2CGBPal1c1 8935
#define kuroihisha2CGBPal1c2 6596
#define kuroihisha2CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define kuroihisha2CGBPal2c0 6076
#define kuroihisha2CGBPal2c1 8935
#define kuroihisha2CGBPal2c2 6596
#define kuroihisha2CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define kuroihisha2CGBPal3c0 6076
#define kuroihisha2CGBPal3c1 8935
#define kuroihisha2CGBPal3c2 6596
#define kuroihisha2CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define kuroihisha2CGBPal4c0 6076
#define kuroihisha2CGBPal4c1 8935
#define kuroihisha2CGBPal4c2 6596
#define kuroihisha2CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define kuroihisha2CGBPal5c0 6076
#define kuroihisha2CGBPal5c1 8935
#define kuroihisha2CGBPal5c2 6596
#define kuroihisha2CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define kuroihisha2CGBPal6c0 6076
#define kuroihisha2CGBPal6c1 8935
#define kuroihisha2CGBPal6c2 6596
#define kuroihisha2CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define kuroihisha2CGBPal7c0 6076
#define kuroihisha2CGBPal7c1 8935
#define kuroihisha2CGBPal7c2 6596
#define kuroihisha2CGBPal7c3 5344

/* SGB palette entries. */
#define kuroihisha2SGB0 0
#define kuroihisha2SGB1 0
#define kuroihisha2SGB2 0
#define kuroihisha2SGB3 0
#define kuroihisha2SGB4 0
#define kuroihisha2SGB5 0
#define kuroihisha2SGB6 0
#define kuroihisha2SGB7 0
#define kuroihisha2SGB8 0
#define kuroihisha2SGB9 0
#define kuroihisha2SGB10 0
#define kuroihisha2SGB11 0
#define kuroihisha2SGB12 0
#define kuroihisha2SGB13 0
#define kuroihisha2SGB14 0
/* Start of tile array. */
extern const unsigned char kuroihisha2[];

#endif

/* End of RACCOONROOK2.H */
