/*

 RACCOONPAWN2.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 16

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __raccoonpawn2_h_INCLUDE
#define __raccoonpawn2_h_INCLUDE

/* Bank of tiles. */
#define kuroifuhyo2Bank 0

/* Super Gameboy palette 0 */
#define kuroifuhyo2SGBPal0c0 32767
#define kuroifuhyo2SGBPal0c1 8728
#define kuroifuhyo2SGBPal0c2 140
#define kuroifuhyo2SGBPal0c3 0

/* Super Gameboy palette 1 */
#define kuroifuhyo2SGBPal1c0 32767
#define kuroifuhyo2SGBPal1c1 671
#define kuroifuhyo2SGBPal1c2 408
#define kuroifuhyo2SGBPal1c3 0

/* Super Gameboy palette 2 */
#define kuroifuhyo2SGBPal2c0 32767
#define kuroifuhyo2SGBPal2c1 8935
#define kuroifuhyo2SGBPal2c2 6596
#define kuroifuhyo2SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define kuroifuhyo2SGBPal3c0 32767
#define kuroifuhyo2SGBPal3c1 8935
#define kuroifuhyo2SGBPal3c2 6596
#define kuroifuhyo2SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define kuroifuhyo2CGBPal0c0 6076
#define kuroifuhyo2CGBPal0c1 8935
#define kuroifuhyo2CGBPal0c2 6596
#define kuroifuhyo2CGBPal0c3 5344

/* Gameboy Color palette 1 */
#define kuroifuhyo2CGBPal1c0 6076
#define kuroifuhyo2CGBPal1c1 8935
#define kuroifuhyo2CGBPal1c2 6596
#define kuroifuhyo2CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define kuroifuhyo2CGBPal2c0 6076
#define kuroifuhyo2CGBPal2c1 8935
#define kuroifuhyo2CGBPal2c2 6596
#define kuroifuhyo2CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define kuroifuhyo2CGBPal3c0 6076
#define kuroifuhyo2CGBPal3c1 8935
#define kuroifuhyo2CGBPal3c2 6596
#define kuroifuhyo2CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define kuroifuhyo2CGBPal4c0 6076
#define kuroifuhyo2CGBPal4c1 8935
#define kuroifuhyo2CGBPal4c2 6596
#define kuroifuhyo2CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define kuroifuhyo2CGBPal5c0 6076
#define kuroifuhyo2CGBPal5c1 8935
#define kuroifuhyo2CGBPal5c2 6596
#define kuroifuhyo2CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define kuroifuhyo2CGBPal6c0 6076
#define kuroifuhyo2CGBPal6c1 8935
#define kuroifuhyo2CGBPal6c2 6596
#define kuroifuhyo2CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define kuroifuhyo2CGBPal7c0 6076
#define kuroifuhyo2CGBPal7c1 8935
#define kuroifuhyo2CGBPal7c2 6596
#define kuroifuhyo2CGBPal7c3 5344

/* SGB palette entries. */
#define kuroifuhyo2SGB0 0
#define kuroifuhyo2SGB1 0
#define kuroifuhyo2SGB2 0
#define kuroifuhyo2SGB3 0
#define kuroifuhyo2SGB4 0
#define kuroifuhyo2SGB5 0
#define kuroifuhyo2SGB6 0
#define kuroifuhyo2SGB7 0
#define kuroifuhyo2SGB8 0
#define kuroifuhyo2SGB9 0
#define kuroifuhyo2SGB10 0
#define kuroifuhyo2SGB11 0
#define kuroifuhyo2SGB12 0
#define kuroifuhyo2SGB13 0
#define kuroifuhyo2SGB14 0
#define kuroifuhyo2SGB15 0
#define kuroifuhyo2SGB16 0
/* Start of tile array. */
extern const unsigned char kuroifuhyo2[];

#endif

/* End of RACCOONPAWN2.H */
