/*

 RACCOONDOWN.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 10

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __raccoondown_h_INCLUDE
#define __raccoondown_h_INCLUDE

/* Bank of tiles. */
#define kuroidefeatedBank 0

/* Super Gameboy palette 0 */
#define kuroidefeatedSGBPal0c0 32767
#define kuroidefeatedSGBPal0c1 8728
#define kuroidefeatedSGBPal0c2 140
#define kuroidefeatedSGBPal0c3 0

/* Super Gameboy palette 1 */
#define kuroidefeatedSGBPal1c0 32767
#define kuroidefeatedSGBPal1c1 671
#define kuroidefeatedSGBPal1c2 408
#define kuroidefeatedSGBPal1c3 0

/* Super Gameboy palette 2 */
#define kuroidefeatedSGBPal2c0 32767
#define kuroidefeatedSGBPal2c1 8935
#define kuroidefeatedSGBPal2c2 6596
#define kuroidefeatedSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define kuroidefeatedSGBPal3c0 32767
#define kuroidefeatedSGBPal3c1 8935
#define kuroidefeatedSGBPal3c2 6596
#define kuroidefeatedSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define kuroidefeatedCGBPal0c0 6076
#define kuroidefeatedCGBPal0c1 8935
#define kuroidefeatedCGBPal0c2 6596
#define kuroidefeatedCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define kuroidefeatedCGBPal1c0 6076
#define kuroidefeatedCGBPal1c1 8935
#define kuroidefeatedCGBPal1c2 6596
#define kuroidefeatedCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define kuroidefeatedCGBPal2c0 6076
#define kuroidefeatedCGBPal2c1 8935
#define kuroidefeatedCGBPal2c2 6596
#define kuroidefeatedCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define kuroidefeatedCGBPal3c0 6076
#define kuroidefeatedCGBPal3c1 8935
#define kuroidefeatedCGBPal3c2 6596
#define kuroidefeatedCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define kuroidefeatedCGBPal4c0 6076
#define kuroidefeatedCGBPal4c1 8935
#define kuroidefeatedCGBPal4c2 6596
#define kuroidefeatedCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define kuroidefeatedCGBPal5c0 6076
#define kuroidefeatedCGBPal5c1 8935
#define kuroidefeatedCGBPal5c2 6596
#define kuroidefeatedCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define kuroidefeatedCGBPal6c0 6076
#define kuroidefeatedCGBPal6c1 8935
#define kuroidefeatedCGBPal6c2 6596
#define kuroidefeatedCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define kuroidefeatedCGBPal7c0 6076
#define kuroidefeatedCGBPal7c1 8935
#define kuroidefeatedCGBPal7c2 6596
#define kuroidefeatedCGBPal7c3 5344

/* SGB palette entries. */
#define kuroidefeatedSGB0 0
#define kuroidefeatedSGB1 0
#define kuroidefeatedSGB2 0
#define kuroidefeatedSGB3 0
#define kuroidefeatedSGB4 0
#define kuroidefeatedSGB5 0
#define kuroidefeatedSGB6 0
#define kuroidefeatedSGB7 0
#define kuroidefeatedSGB8 0
#define kuroidefeatedSGB9 0
#define kuroidefeatedSGB10 0
/* Start of tile array. */
extern const unsigned char kuroidefeated[];

#endif

/* End of RACCOONDOWN.H */
