/*

 RACCOONSILVER1.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 14

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __raccoonsilver1_h_INCLUDE
#define __raccoonsilver1_h_INCLUDE

/* Bank of tiles. */
#define kuroiginshou1Bank 0

/* Super Gameboy palette 0 */
#define kuroiginshou1SGBPal0c0 32767
#define kuroiginshou1SGBPal0c1 8728
#define kuroiginshou1SGBPal0c2 140
#define kuroiginshou1SGBPal0c3 0

/* Super Gameboy palette 1 */
#define kuroiginshou1SGBPal1c0 32767
#define kuroiginshou1SGBPal1c1 671
#define kuroiginshou1SGBPal1c2 408
#define kuroiginshou1SGBPal1c3 0

/* Super Gameboy palette 2 */
#define kuroiginshou1SGBPal2c0 32767
#define kuroiginshou1SGBPal2c1 8935
#define kuroiginshou1SGBPal2c2 6596
#define kuroiginshou1SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define kuroiginshou1SGBPal3c0 32767
#define kuroiginshou1SGBPal3c1 8935
#define kuroiginshou1SGBPal3c2 6596
#define kuroiginshou1SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define kuroiginshou1CGBPal0c0 6076
#define kuroiginshou1CGBPal0c1 8935
#define kuroiginshou1CGBPal0c2 6596
#define kuroiginshou1CGBPal0c3 5344

/* Gameboy Color palette 1 */
#define kuroiginshou1CGBPal1c0 6076
#define kuroiginshou1CGBPal1c1 8935
#define kuroiginshou1CGBPal1c2 6596
#define kuroiginshou1CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define kuroiginshou1CGBPal2c0 6076
#define kuroiginshou1CGBPal2c1 8935
#define kuroiginshou1CGBPal2c2 6596
#define kuroiginshou1CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define kuroiginshou1CGBPal3c0 6076
#define kuroiginshou1CGBPal3c1 8935
#define kuroiginshou1CGBPal3c2 6596
#define kuroiginshou1CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define kuroiginshou1CGBPal4c0 6076
#define kuroiginshou1CGBPal4c1 8935
#define kuroiginshou1CGBPal4c2 6596
#define kuroiginshou1CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define kuroiginshou1CGBPal5c0 6076
#define kuroiginshou1CGBPal5c1 8935
#define kuroiginshou1CGBPal5c2 6596
#define kuroiginshou1CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define kuroiginshou1CGBPal6c0 6076
#define kuroiginshou1CGBPal6c1 8935
#define kuroiginshou1CGBPal6c2 6596
#define kuroiginshou1CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define kuroiginshou1CGBPal7c0 6076
#define kuroiginshou1CGBPal7c1 8935
#define kuroiginshou1CGBPal7c2 6596
#define kuroiginshou1CGBPal7c3 5344

/* SGB palette entries. */
#define kuroiginshou1SGB0 0
#define kuroiginshou1SGB1 0
#define kuroiginshou1SGB2 0
#define kuroiginshou1SGB3 0
#define kuroiginshou1SGB4 0
#define kuroiginshou1SGB5 0
#define kuroiginshou1SGB6 0
#define kuroiginshou1SGB7 0
#define kuroiginshou1SGB8 0
#define kuroiginshou1SGB9 0
#define kuroiginshou1SGB10 0
#define kuroiginshou1SGB11 0
#define kuroiginshou1SGB12 0
#define kuroiginshou1SGB13 0
#define kuroiginshou1SGB14 0
/* Start of tile array. */
extern const unsigned char kuroiginshou1[];

#endif

/* End of RACCOONSILVER1.H */
