/*

 SHOGIMENUTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 201

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Shogimenutiles_h_INCLUDE
#define __Shogimenutiles_h_INCLUDE

/* Bank of tiles. */
#define shogidatamenuBank 0

/* Super Gameboy palette 0 */
#define shogidatamenuSGBPal0c0 21374
#define shogidatamenuSGBPal0c1 16089
#define shogidatamenuSGBPal0c2 10804
#define shogidatamenuSGBPal0c3 234

/* Super Gameboy palette 1 */
#define shogidatamenuSGBPal1c0 21374
#define shogidatamenuSGBPal1c1 31705
#define shogidatamenuSGBPal1c2 31540
#define shogidatamenuSGBPal1c3 26255

/* Super Gameboy palette 2 */
#define shogidatamenuSGBPal2c0 21374
#define shogidatamenuSGBPal2c1 31
#define shogidatamenuSGBPal2c2 21
#define shogidatamenuSGBPal2c3 11

/* Super Gameboy palette 3 */
#define shogidatamenuSGBPal3c0 21374
#define shogidatamenuSGBPal3c1 8935
#define shogidatamenuSGBPal3c2 6596
#define shogidatamenuSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define shogidatamenuCGBPal0c0 6076
#define shogidatamenuCGBPal0c1 8935
#define shogidatamenuCGBPal0c2 6596
#define shogidatamenuCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define shogidatamenuCGBPal1c0 6076
#define shogidatamenuCGBPal1c1 8935
#define shogidatamenuCGBPal1c2 6596
#define shogidatamenuCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define shogidatamenuCGBPal2c0 6076
#define shogidatamenuCGBPal2c1 8935
#define shogidatamenuCGBPal2c2 6596
#define shogidatamenuCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define shogidatamenuCGBPal3c0 6076
#define shogidatamenuCGBPal3c1 8935
#define shogidatamenuCGBPal3c2 6596
#define shogidatamenuCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define shogidatamenuCGBPal4c0 6076
#define shogidatamenuCGBPal4c1 8935
#define shogidatamenuCGBPal4c2 6596
#define shogidatamenuCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define shogidatamenuCGBPal5c0 6076
#define shogidatamenuCGBPal5c1 8935
#define shogidatamenuCGBPal5c2 6596
#define shogidatamenuCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define shogidatamenuCGBPal6c0 6076
#define shogidatamenuCGBPal6c1 8935
#define shogidatamenuCGBPal6c2 6596
#define shogidatamenuCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define shogidatamenuCGBPal7c0 6076
#define shogidatamenuCGBPal7c1 8935
#define shogidatamenuCGBPal7c2 6596
#define shogidatamenuCGBPal7c3 5344

/* SGB palette entries. */
#define shogidatamenuSGB0 0
#define shogidatamenuSGB1 0
#define shogidatamenuSGB2 0
#define shogidatamenuSGB3 0
#define shogidatamenuSGB4 0
#define shogidatamenuSGB5 0
#define shogidatamenuSGB6 0
#define shogidatamenuSGB7 0
#define shogidatamenuSGB8 0
#define shogidatamenuSGB9 0
#define shogidatamenuSGB10 0
#define shogidatamenuSGB11 0
#define shogidatamenuSGB12 0
#define shogidatamenuSGB13 0
#define shogidatamenuSGB14 0
#define shogidatamenuSGB15 0
#define shogidatamenuSGB16 0
#define shogidatamenuSGB17 0
#define shogidatamenuSGB18 0
#define shogidatamenuSGB19 0
#define shogidatamenuSGB20 0
#define shogidatamenuSGB21 0
#define shogidatamenuSGB22 0
#define shogidatamenuSGB23 0
#define shogidatamenuSGB24 0
#define shogidatamenuSGB25 0
#define shogidatamenuSGB26 0
#define shogidatamenuSGB27 0
#define shogidatamenuSGB28 0
#define shogidatamenuSGB29 0
#define shogidatamenuSGB30 0
#define shogidatamenuSGB31 0
#define shogidatamenuSGB32 0
#define shogidatamenuSGB33 0
#define shogidatamenuSGB34 0
#define shogidatamenuSGB35 0
#define shogidatamenuSGB36 0
#define shogidatamenuSGB37 0
#define shogidatamenuSGB38 0
#define shogidatamenuSGB39 0
#define shogidatamenuSGB40 0
#define shogidatamenuSGB41 0
#define shogidatamenuSGB42 0
#define shogidatamenuSGB43 0
#define shogidatamenuSGB44 0
#define shogidatamenuSGB45 0
#define shogidatamenuSGB46 0
#define shogidatamenuSGB47 0
#define shogidatamenuSGB48 0
#define shogidatamenuSGB49 0
#define shogidatamenuSGB50 0
#define shogidatamenuSGB51 0
#define shogidatamenuSGB52 0
#define shogidatamenuSGB53 0
#define shogidatamenuSGB54 0
#define shogidatamenuSGB55 0
#define shogidatamenuSGB56 0
#define shogidatamenuSGB57 0
#define shogidatamenuSGB58 0
#define shogidatamenuSGB59 0
#define shogidatamenuSGB60 0
#define shogidatamenuSGB61 0
#define shogidatamenuSGB62 0
#define shogidatamenuSGB63 0
#define shogidatamenuSGB64 0
#define shogidatamenuSGB65 0
#define shogidatamenuSGB66 0
#define shogidatamenuSGB67 0
#define shogidatamenuSGB68 0
#define shogidatamenuSGB69 0
#define shogidatamenuSGB70 0
#define shogidatamenuSGB71 0
#define shogidatamenuSGB72 0
#define shogidatamenuSGB73 0
#define shogidatamenuSGB74 0
#define shogidatamenuSGB75 0
#define shogidatamenuSGB76 0
#define shogidatamenuSGB77 0
#define shogidatamenuSGB78 0
#define shogidatamenuSGB79 0
#define shogidatamenuSGB80 0
#define shogidatamenuSGB81 0
#define shogidatamenuSGB82 0
#define shogidatamenuSGB83 0
#define shogidatamenuSGB84 0
#define shogidatamenuSGB85 0
#define shogidatamenuSGB86 0
#define shogidatamenuSGB87 0
#define shogidatamenuSGB88 0
#define shogidatamenuSGB89 0
#define shogidatamenuSGB90 0
#define shogidatamenuSGB91 0
#define shogidatamenuSGB92 0
#define shogidatamenuSGB93 0
#define shogidatamenuSGB94 0
#define shogidatamenuSGB95 0
#define shogidatamenuSGB96 0
#define shogidatamenuSGB97 0
#define shogidatamenuSGB98 0
#define shogidatamenuSGB99 0
#define shogidatamenuSGB100 0
#define shogidatamenuSGB101 0
#define shogidatamenuSGB102 0
#define shogidatamenuSGB103 0
#define shogidatamenuSGB104 0
#define shogidatamenuSGB105 0
#define shogidatamenuSGB106 0
#define shogidatamenuSGB107 0
#define shogidatamenuSGB108 0
#define shogidatamenuSGB109 0
#define shogidatamenuSGB110 0
#define shogidatamenuSGB111 0
#define shogidatamenuSGB112 0
#define shogidatamenuSGB113 0
#define shogidatamenuSGB114 0
#define shogidatamenuSGB115 0
#define shogidatamenuSGB116 0
#define shogidatamenuSGB117 0
#define shogidatamenuSGB118 0
#define shogidatamenuSGB119 0
#define shogidatamenuSGB120 0
#define shogidatamenuSGB121 0
#define shogidatamenuSGB122 0
#define shogidatamenuSGB123 0
#define shogidatamenuSGB124 0
#define shogidatamenuSGB125 0
#define shogidatamenuSGB126 0
#define shogidatamenuSGB127 0
#define shogidatamenuSGB128 0
#define shogidatamenuSGB129 0
#define shogidatamenuSGB130 0
#define shogidatamenuSGB131 0
#define shogidatamenuSGB132 0
#define shogidatamenuSGB133 0
#define shogidatamenuSGB134 0
#define shogidatamenuSGB135 0
#define shogidatamenuSGB136 0
#define shogidatamenuSGB137 0
#define shogidatamenuSGB138 0
#define shogidatamenuSGB139 0
#define shogidatamenuSGB140 0
#define shogidatamenuSGB141 0
#define shogidatamenuSGB142 0
#define shogidatamenuSGB143 0
#define shogidatamenuSGB144 0
#define shogidatamenuSGB145 0
#define shogidatamenuSGB146 0
#define shogidatamenuSGB147 0
#define shogidatamenuSGB148 0
#define shogidatamenuSGB149 0
#define shogidatamenuSGB150 0
#define shogidatamenuSGB151 0
#define shogidatamenuSGB152 0
#define shogidatamenuSGB153 0
#define shogidatamenuSGB154 0
#define shogidatamenuSGB155 0
#define shogidatamenuSGB156 0
#define shogidatamenuSGB157 0
#define shogidatamenuSGB158 0
#define shogidatamenuSGB159 0
#define shogidatamenuSGB160 0
#define shogidatamenuSGB161 0
#define shogidatamenuSGB162 0
#define shogidatamenuSGB163 0
#define shogidatamenuSGB164 0
#define shogidatamenuSGB165 0
#define shogidatamenuSGB166 0
#define shogidatamenuSGB167 0
#define shogidatamenuSGB168 0
#define shogidatamenuSGB169 0
#define shogidatamenuSGB170 0
#define shogidatamenuSGB171 0
#define shogidatamenuSGB172 0
#define shogidatamenuSGB173 0
#define shogidatamenuSGB174 0
#define shogidatamenuSGB175 0
#define shogidatamenuSGB176 0
#define shogidatamenuSGB177 0
#define shogidatamenuSGB178 0
#define shogidatamenuSGB179 0
#define shogidatamenuSGB180 0
#define shogidatamenuSGB181 0
#define shogidatamenuSGB182 0
#define shogidatamenuSGB183 0
#define shogidatamenuSGB184 0
#define shogidatamenuSGB185 0
#define shogidatamenuSGB186 0
#define shogidatamenuSGB187 0
#define shogidatamenuSGB188 0
#define shogidatamenuSGB189 0
#define shogidatamenuSGB190 0
#define shogidatamenuSGB191 0
#define shogidatamenuSGB192 0
#define shogidatamenuSGB193 0
#define shogidatamenuSGB194 0
#define shogidatamenuSGB195 0
#define shogidatamenuSGB196 0
#define shogidatamenuSGB197 0
#define shogidatamenuSGB198 0
#define shogidatamenuSGB199 0
#define shogidatamenuSGB200 0
#define shogidatamenuSGB201 0
/* Start of tile array. */
extern const unsigned char shogidatamenu[];

#endif

/* End of SHOGIMENUTILES.H */
