/*

 SHOGITITLE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 218

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Shogititle_h_INCLUDE
#define __Shogititle_h_INCLUDE

/* Bank of tiles. */
#define titletilesBank 0

/* Super Gameboy palette 0 */
#define titletilesSGBPal0c0 6076
#define titletilesSGBPal0c1 8935
#define titletilesSGBPal0c2 6596
#define titletilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define titletilesSGBPal1c0 6076
#define titletilesSGBPal1c1 8935
#define titletilesSGBPal1c2 6596
#define titletilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define titletilesSGBPal2c0 6076
#define titletilesSGBPal2c1 8935
#define titletilesSGBPal2c2 6596
#define titletilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define titletilesSGBPal3c0 6076
#define titletilesSGBPal3c1 8935
#define titletilesSGBPal3c2 6596
#define titletilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define titletilesCGBPal0c0 6076
#define titletilesCGBPal0c1 8935
#define titletilesCGBPal0c2 6596
#define titletilesCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define titletilesCGBPal1c0 6076
#define titletilesCGBPal1c1 8935
#define titletilesCGBPal1c2 6596
#define titletilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define titletilesCGBPal2c0 6076
#define titletilesCGBPal2c1 8935
#define titletilesCGBPal2c2 6596
#define titletilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define titletilesCGBPal3c0 6076
#define titletilesCGBPal3c1 8935
#define titletilesCGBPal3c2 6596
#define titletilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define titletilesCGBPal4c0 6076
#define titletilesCGBPal4c1 8935
#define titletilesCGBPal4c2 6596
#define titletilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define titletilesCGBPal5c0 6076
#define titletilesCGBPal5c1 8935
#define titletilesCGBPal5c2 6596
#define titletilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define titletilesCGBPal6c0 6076
#define titletilesCGBPal6c1 8935
#define titletilesCGBPal6c2 6596
#define titletilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define titletilesCGBPal7c0 6076
#define titletilesCGBPal7c1 8935
#define titletilesCGBPal7c2 6596
#define titletilesCGBPal7c3 5344

/* SGB palette entries. */
#define titletilesSGB0 0
#define titletilesSGB1 0
#define titletilesSGB2 0
#define titletilesSGB3 0
#define titletilesSGB4 0
#define titletilesSGB5 0
#define titletilesSGB6 0
#define titletilesSGB7 0
#define titletilesSGB8 0
#define titletilesSGB9 0
#define titletilesSGB10 0
#define titletilesSGB11 0
#define titletilesSGB12 0
#define titletilesSGB13 0
#define titletilesSGB14 0
#define titletilesSGB15 0
#define titletilesSGB16 0
#define titletilesSGB17 0
#define titletilesSGB18 0
#define titletilesSGB19 0
#define titletilesSGB20 0
#define titletilesSGB21 0
#define titletilesSGB22 0
#define titletilesSGB23 0
#define titletilesSGB24 0
#define titletilesSGB25 0
#define titletilesSGB26 0
#define titletilesSGB27 0
#define titletilesSGB28 0
#define titletilesSGB29 0
#define titletilesSGB30 0
#define titletilesSGB31 0
#define titletilesSGB32 0
#define titletilesSGB33 0
#define titletilesSGB34 0
#define titletilesSGB35 0
#define titletilesSGB36 0
#define titletilesSGB37 0
#define titletilesSGB38 0
#define titletilesSGB39 0
#define titletilesSGB40 0
#define titletilesSGB41 0
#define titletilesSGB42 0
#define titletilesSGB43 0
#define titletilesSGB44 0
#define titletilesSGB45 0
#define titletilesSGB46 0
#define titletilesSGB47 0
#define titletilesSGB48 0
#define titletilesSGB49 0
#define titletilesSGB50 0
#define titletilesSGB51 0
#define titletilesSGB52 0
#define titletilesSGB53 0
#define titletilesSGB54 0
#define titletilesSGB55 0
#define titletilesSGB56 0
#define titletilesSGB57 0
#define titletilesSGB58 0
#define titletilesSGB59 0
#define titletilesSGB60 0
#define titletilesSGB61 0
#define titletilesSGB62 0
#define titletilesSGB63 0
#define titletilesSGB64 0
#define titletilesSGB65 0
#define titletilesSGB66 0
#define titletilesSGB67 0
#define titletilesSGB68 0
#define titletilesSGB69 0
#define titletilesSGB70 0
#define titletilesSGB71 0
#define titletilesSGB72 0
#define titletilesSGB73 0
#define titletilesSGB74 0
#define titletilesSGB75 0
#define titletilesSGB76 0
#define titletilesSGB77 0
#define titletilesSGB78 0
#define titletilesSGB79 0
#define titletilesSGB80 0
#define titletilesSGB81 0
#define titletilesSGB82 0
#define titletilesSGB83 0
#define titletilesSGB84 0
#define titletilesSGB85 0
#define titletilesSGB86 0
#define titletilesSGB87 0
#define titletilesSGB88 0
#define titletilesSGB89 0
#define titletilesSGB90 0
#define titletilesSGB91 0
#define titletilesSGB92 0
#define titletilesSGB93 0
#define titletilesSGB94 0
#define titletilesSGB95 0
#define titletilesSGB96 0
#define titletilesSGB97 0
#define titletilesSGB98 0
#define titletilesSGB99 0
#define titletilesSGB100 0
#define titletilesSGB101 0
#define titletilesSGB102 0
#define titletilesSGB103 0
#define titletilesSGB104 0
#define titletilesSGB105 0
#define titletilesSGB106 0
#define titletilesSGB107 0
#define titletilesSGB108 0
#define titletilesSGB109 0
#define titletilesSGB110 0
#define titletilesSGB111 0
#define titletilesSGB112 0
#define titletilesSGB113 0
#define titletilesSGB114 0
#define titletilesSGB115 0
#define titletilesSGB116 0
#define titletilesSGB117 0
#define titletilesSGB118 0
#define titletilesSGB119 0
#define titletilesSGB120 0
#define titletilesSGB121 0
#define titletilesSGB122 0
#define titletilesSGB123 0
#define titletilesSGB124 0
#define titletilesSGB125 0
#define titletilesSGB126 0
#define titletilesSGB127 0
#define titletilesSGB128 0
#define titletilesSGB129 0
#define titletilesSGB130 0
#define titletilesSGB131 0
#define titletilesSGB132 0
#define titletilesSGB133 0
#define titletilesSGB134 0
#define titletilesSGB135 0
#define titletilesSGB136 0
#define titletilesSGB137 0
#define titletilesSGB138 0
#define titletilesSGB139 0
#define titletilesSGB140 0
#define titletilesSGB141 0
#define titletilesSGB142 0
#define titletilesSGB143 0
#define titletilesSGB144 0
#define titletilesSGB145 0
#define titletilesSGB146 0
#define titletilesSGB147 0
#define titletilesSGB148 0
#define titletilesSGB149 0
#define titletilesSGB150 0
#define titletilesSGB151 0
#define titletilesSGB152 0
#define titletilesSGB153 0
#define titletilesSGB154 0
#define titletilesSGB155 0
#define titletilesSGB156 0
#define titletilesSGB157 0
#define titletilesSGB158 0
#define titletilesSGB159 0
#define titletilesSGB160 0
#define titletilesSGB161 0
#define titletilesSGB162 0
#define titletilesSGB163 0
#define titletilesSGB164 0
#define titletilesSGB165 0
#define titletilesSGB166 0
#define titletilesSGB167 0
#define titletilesSGB168 0
#define titletilesSGB169 0
#define titletilesSGB170 0
#define titletilesSGB171 0
#define titletilesSGB172 0
#define titletilesSGB173 0
#define titletilesSGB174 0
#define titletilesSGB175 0
#define titletilesSGB176 0
#define titletilesSGB177 0
#define titletilesSGB178 0
#define titletilesSGB179 0
#define titletilesSGB180 0
#define titletilesSGB181 0
#define titletilesSGB182 0
#define titletilesSGB183 0
#define titletilesSGB184 0
#define titletilesSGB185 0
#define titletilesSGB186 0
#define titletilesSGB187 0
#define titletilesSGB188 0
#define titletilesSGB189 0
#define titletilesSGB190 0
#define titletilesSGB191 0
#define titletilesSGB192 0
#define titletilesSGB193 0
#define titletilesSGB194 0
#define titletilesSGB195 0
#define titletilesSGB196 0
#define titletilesSGB197 0
#define titletilesSGB198 0
#define titletilesSGB199 0
#define titletilesSGB200 0
#define titletilesSGB201 0
#define titletilesSGB202 0
#define titletilesSGB203 0
#define titletilesSGB204 0
#define titletilesSGB205 0
#define titletilesSGB206 0
#define titletilesSGB207 0
#define titletilesSGB208 0
#define titletilesSGB209 0
#define titletilesSGB210 0
#define titletilesSGB211 0
#define titletilesSGB212 0
#define titletilesSGB213 0
#define titletilesSGB214 0
#define titletilesSGB215 0
#define titletilesSGB216 0
#define titletilesSGB217 0
#define titletilesSGB218 0
/* Start of tile array. */
extern const unsigned char titletiles[];

#endif

/* End of SHOGITITLE.H */
