/*

 SHOGITITLESCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 2
   Map size      : 20 x 18
   Tile set      : E:\Projects\GoGoShogi\titlescreen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Shogititlescreen_h_INCLUDE
#define __Shogititlescreen_h_INCLUDE

#define titlesceneWidth 20
#define titlesceneHeight 18
#define titlesceneBank 2

#define titlescene titlescenePLN0
extern const unsigned char titlescenePLN0[];

#endif

/* End of SHOGITITLESCREEN.H */
