/*

 SHOGITILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 202

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Shogitiles_h_INCLUDE
#define __Shogitiles_h_INCLUDE

/* Bank of tiles. */
#define shogidataBank 0

/* Super Gameboy palette 0 */
#define shogidataSGBPal0c0 21374
#define shogidataSGBPal0c1 16089
#define shogidataSGBPal0c2 10804
#define shogidataSGBPal0c3 234

/* Super Gameboy palette 1 */
#define shogidataSGBPal1c0 21374
#define shogidataSGBPal1c1 31705
#define shogidataSGBPal1c2 31540
#define shogidataSGBPal1c3 26255

/* Super Gameboy palette 2 */
#define shogidataSGBPal2c0 21374
#define shogidataSGBPal2c1 31
#define shogidataSGBPal2c2 21
#define shogidataSGBPal2c3 11

/* Super Gameboy palette 3 */
#define shogidataSGBPal3c0 21374
#define shogidataSGBPal3c1 8935
#define shogidataSGBPal3c2 6596
#define shogidataSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define shogidataCGBPal0c0 6076
#define shogidataCGBPal0c1 8935
#define shogidataCGBPal0c2 6596
#define shogidataCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define shogidataCGBPal1c0 6076
#define shogidataCGBPal1c1 8935
#define shogidataCGBPal1c2 6596
#define shogidataCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define shogidataCGBPal2c0 6076
#define shogidataCGBPal2c1 8935
#define shogidataCGBPal2c2 6596
#define shogidataCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define shogidataCGBPal3c0 6076
#define shogidataCGBPal3c1 8935
#define shogidataCGBPal3c2 6596
#define shogidataCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define shogidataCGBPal4c0 6076
#define shogidataCGBPal4c1 8935
#define shogidataCGBPal4c2 6596
#define shogidataCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define shogidataCGBPal5c0 6076
#define shogidataCGBPal5c1 8935
#define shogidataCGBPal5c2 6596
#define shogidataCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define shogidataCGBPal6c0 6076
#define shogidataCGBPal6c1 8935
#define shogidataCGBPal6c2 6596
#define shogidataCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define shogidataCGBPal7c0 6076
#define shogidataCGBPal7c1 8935
#define shogidataCGBPal7c2 6596
#define shogidataCGBPal7c3 5344

/* SGB palette entries. */
#define shogidataSGB0 0
#define shogidataSGB1 0
#define shogidataSGB2 0
#define shogidataSGB3 0
#define shogidataSGB4 0
#define shogidataSGB5 0
#define shogidataSGB6 0
#define shogidataSGB7 0
#define shogidataSGB8 0
#define shogidataSGB9 0
#define shogidataSGB10 0
#define shogidataSGB11 0
#define shogidataSGB12 0
#define shogidataSGB13 0
#define shogidataSGB14 0
#define shogidataSGB15 0
#define shogidataSGB16 0
#define shogidataSGB17 0
#define shogidataSGB18 0
#define shogidataSGB19 0
#define shogidataSGB20 0
#define shogidataSGB21 0
#define shogidataSGB22 0
#define shogidataSGB23 0
#define shogidataSGB24 0
#define shogidataSGB25 0
#define shogidataSGB26 0
#define shogidataSGB27 0
#define shogidataSGB28 0
#define shogidataSGB29 0
#define shogidataSGB30 0
#define shogidataSGB31 0
#define shogidataSGB32 0
#define shogidataSGB33 0
#define shogidataSGB34 0
#define shogidataSGB35 0
#define shogidataSGB36 0
#define shogidataSGB37 0
#define shogidataSGB38 0
#define shogidataSGB39 0
#define shogidataSGB40 0
#define shogidataSGB41 0
#define shogidataSGB42 0
#define shogidataSGB43 0
#define shogidataSGB44 0
#define shogidataSGB45 0
#define shogidataSGB46 0
#define shogidataSGB47 0
#define shogidataSGB48 0
#define shogidataSGB49 0
#define shogidataSGB50 0
#define shogidataSGB51 0
#define shogidataSGB52 0
#define shogidataSGB53 0
#define shogidataSGB54 0
#define shogidataSGB55 0
#define shogidataSGB56 0
#define shogidataSGB57 0
#define shogidataSGB58 0
#define shogidataSGB59 0
#define shogidataSGB60 0
#define shogidataSGB61 0
#define shogidataSGB62 0
#define shogidataSGB63 0
#define shogidataSGB64 0
#define shogidataSGB65 0
#define shogidataSGB66 0
#define shogidataSGB67 0
#define shogidataSGB68 0
#define shogidataSGB69 0
#define shogidataSGB70 0
#define shogidataSGB71 0
#define shogidataSGB72 0
#define shogidataSGB73 0
#define shogidataSGB74 0
#define shogidataSGB75 0
#define shogidataSGB76 0
#define shogidataSGB77 0
#define shogidataSGB78 0
#define shogidataSGB79 0
#define shogidataSGB80 0
#define shogidataSGB81 0
#define shogidataSGB82 0
#define shogidataSGB83 0
#define shogidataSGB84 0
#define shogidataSGB85 0
#define shogidataSGB86 0
#define shogidataSGB87 0
#define shogidataSGB88 0
#define shogidataSGB89 0
#define shogidataSGB90 0
#define shogidataSGB91 0
#define shogidataSGB92 0
#define shogidataSGB93 0
#define shogidataSGB94 0
#define shogidataSGB95 0
#define shogidataSGB96 0
#define shogidataSGB97 0
#define shogidataSGB98 0
#define shogidataSGB99 0
#define shogidataSGB100 0
#define shogidataSGB101 0
#define shogidataSGB102 0
#define shogidataSGB103 0
#define shogidataSGB104 0
#define shogidataSGB105 0
#define shogidataSGB106 0
#define shogidataSGB107 0
#define shogidataSGB108 0
#define shogidataSGB109 0
#define shogidataSGB110 0
#define shogidataSGB111 0
#define shogidataSGB112 0
#define shogidataSGB113 0
#define shogidataSGB114 0
#define shogidataSGB115 0
#define shogidataSGB116 0
#define shogidataSGB117 0
#define shogidataSGB118 0
#define shogidataSGB119 0
#define shogidataSGB120 0
#define shogidataSGB121 0
#define shogidataSGB122 0
#define shogidataSGB123 0
#define shogidataSGB124 0
#define shogidataSGB125 0
#define shogidataSGB126 0
#define shogidataSGB127 0
#define shogidataSGB128 0
#define shogidataSGB129 0
#define shogidataSGB130 0
#define shogidataSGB131 0
#define shogidataSGB132 0
#define shogidataSGB133 0
#define shogidataSGB134 0
#define shogidataSGB135 0
#define shogidataSGB136 0
#define shogidataSGB137 0
#define shogidataSGB138 0
#define shogidataSGB139 0
#define shogidataSGB140 0
#define shogidataSGB141 0
#define shogidataSGB142 0
#define shogidataSGB143 0
#define shogidataSGB144 0
#define shogidataSGB145 0
#define shogidataSGB146 0
#define shogidataSGB147 0
#define shogidataSGB148 0
#define shogidataSGB149 0
#define shogidataSGB150 0
#define shogidataSGB151 0
#define shogidataSGB152 0
#define shogidataSGB153 0
#define shogidataSGB154 0
#define shogidataSGB155 0
#define shogidataSGB156 0
#define shogidataSGB157 0
#define shogidataSGB158 0
#define shogidataSGB159 0
#define shogidataSGB160 0
#define shogidataSGB161 0
#define shogidataSGB162 0
#define shogidataSGB163 0
#define shogidataSGB164 0
#define shogidataSGB165 0
#define shogidataSGB166 0
#define shogidataSGB167 0
#define shogidataSGB168 0
#define shogidataSGB169 0
#define shogidataSGB170 0
#define shogidataSGB171 0
#define shogidataSGB172 0
#define shogidataSGB173 0
#define shogidataSGB174 0
#define shogidataSGB175 0
#define shogidataSGB176 0
#define shogidataSGB177 0
#define shogidataSGB178 0
#define shogidataSGB179 0
#define shogidataSGB180 0
#define shogidataSGB181 0
#define shogidataSGB182 0
#define shogidataSGB183 0
#define shogidataSGB184 0
#define shogidataSGB185 0
#define shogidataSGB186 0
#define shogidataSGB187 0
#define shogidataSGB188 0
#define shogidataSGB189 0
#define shogidataSGB190 0
#define shogidataSGB191 0
#define shogidataSGB192 0
#define shogidataSGB193 0
#define shogidataSGB194 0
#define shogidataSGB195 0
#define shogidataSGB196 0
#define shogidataSGB197 0
#define shogidataSGB198 0
#define shogidataSGB199 0
#define shogidataSGB200 0
#define shogidataSGB201 0
#define shogidataSGB202 0
/* Start of tile array. */
extern const unsigned char shogidata[];

#endif

/* End of SHOGITILES.H */
