/*

 SHOGIOBJECTS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 76

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __shogiobjects_h_INCLUDE
#define __shogiobjects_h_INCLUDE

/* Bank of tiles. */
#define ObjectBank 0

/* Super Gameboy palette 0 */
#define ObjectSGBPal0c0 21374
#define ObjectSGBPal0c1 16089
#define ObjectSGBPal0c2 10804
#define ObjectSGBPal0c3 234

/* Super Gameboy palette 1 */
#define ObjectSGBPal1c0 21374
#define ObjectSGBPal1c1 31705
#define ObjectSGBPal1c2 31540
#define ObjectSGBPal1c3 26255

/* Super Gameboy palette 2 */
#define ObjectSGBPal2c0 21374
#define ObjectSGBPal2c1 31
#define ObjectSGBPal2c2 21
#define ObjectSGBPal2c3 11

/* Super Gameboy palette 3 */
#define ObjectSGBPal3c0 21374
#define ObjectSGBPal3c1 8935
#define ObjectSGBPal3c2 6596
#define ObjectSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define ObjectCGBPal0c0 6076
#define ObjectCGBPal0c1 8935
#define ObjectCGBPal0c2 6596
#define ObjectCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define ObjectCGBPal1c0 6076
#define ObjectCGBPal1c1 8935
#define ObjectCGBPal1c2 6596
#define ObjectCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define ObjectCGBPal2c0 6076
#define ObjectCGBPal2c1 8935
#define ObjectCGBPal2c2 6596
#define ObjectCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define ObjectCGBPal3c0 6076
#define ObjectCGBPal3c1 8935
#define ObjectCGBPal3c2 6596
#define ObjectCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define ObjectCGBPal4c0 6076
#define ObjectCGBPal4c1 8935
#define ObjectCGBPal4c2 6596
#define ObjectCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define ObjectCGBPal5c0 6076
#define ObjectCGBPal5c1 8935
#define ObjectCGBPal5c2 6596
#define ObjectCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define ObjectCGBPal6c0 6076
#define ObjectCGBPal6c1 8935
#define ObjectCGBPal6c2 6596
#define ObjectCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define ObjectCGBPal7c0 6076
#define ObjectCGBPal7c1 8935
#define ObjectCGBPal7c2 6596
#define ObjectCGBPal7c3 5344

/* SGB palette entries. */
#define ObjectSGB0 0
#define ObjectSGB1 0
#define ObjectSGB2 0
#define ObjectSGB3 0
#define ObjectSGB4 0
#define ObjectSGB5 0
#define ObjectSGB6 0
#define ObjectSGB7 0
#define ObjectSGB8 0
#define ObjectSGB9 0
#define ObjectSGB10 0
#define ObjectSGB11 0
#define ObjectSGB12 0
#define ObjectSGB13 0
#define ObjectSGB14 0
#define ObjectSGB15 0
#define ObjectSGB16 0
#define ObjectSGB17 0
#define ObjectSGB18 0
#define ObjectSGB19 0
#define ObjectSGB20 0
#define ObjectSGB21 0
#define ObjectSGB22 0
#define ObjectSGB23 0
#define ObjectSGB24 0
#define ObjectSGB25 0
#define ObjectSGB26 0
#define ObjectSGB27 0
#define ObjectSGB28 0
#define ObjectSGB29 0
#define ObjectSGB30 0
#define ObjectSGB31 0
#define ObjectSGB32 0
#define ObjectSGB33 0
#define ObjectSGB34 0
#define ObjectSGB35 0
#define ObjectSGB36 0
#define ObjectSGB37 0
#define ObjectSGB38 0
#define ObjectSGB39 0
#define ObjectSGB40 0
#define ObjectSGB41 0
#define ObjectSGB42 0
#define ObjectSGB43 0
#define ObjectSGB44 0
#define ObjectSGB45 0
#define ObjectSGB46 0
#define ObjectSGB47 0
#define ObjectSGB48 0
#define ObjectSGB49 0
#define ObjectSGB50 0
#define ObjectSGB51 0
#define ObjectSGB52 1
#define ObjectSGB53 1
#define ObjectSGB54 1
#define ObjectSGB55 1
#define ObjectSGB56 1
#define ObjectSGB57 1
#define ObjectSGB58 1
#define ObjectSGB59 1
#define ObjectSGB60 1
#define ObjectSGB61 1
#define ObjectSGB62 1
#define ObjectSGB63 1
#define ObjectSGB64 1
#define ObjectSGB65 1
#define ObjectSGB66 1
#define ObjectSGB67 1
#define ObjectSGB68 1
#define ObjectSGB69 1
#define ObjectSGB70 1
#define ObjectSGB71 1
#define ObjectSGB72 2
#define ObjectSGB73 2
#define ObjectSGB74 2
#define ObjectSGB75 2
#define ObjectSGB76 2
/* Start of tile array. */
extern const unsigned char Object[];

#endif

/* End of SHOGIOBJECTS.H */
