/*

 SILVERSILVERSWORD.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 17

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __silversilversword_h_INCLUDE
#define __silversilversword_h_INCLUDE

/* Bank of tiles. */
#define shiroiginshouslashBank 0

/* Super Gameboy palette 0 */
#define shiroiginshouslashSGBPal0c0 32767
#define shiroiginshouslashSGBPal0c1 25368
#define shiroiginshouslashSGBPal0c2 12684
#define shiroiginshouslashSGBPal0c3 0

/* Super Gameboy palette 1 */
#define shiroiginshouslashSGBPal1c0 32767
#define shiroiginshouslashSGBPal1c1 8935
#define shiroiginshouslashSGBPal1c2 6596
#define shiroiginshouslashSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define shiroiginshouslashSGBPal2c0 32767
#define shiroiginshouslashSGBPal2c1 8935
#define shiroiginshouslashSGBPal2c2 6596
#define shiroiginshouslashSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define shiroiginshouslashSGBPal3c0 32767
#define shiroiginshouslashSGBPal3c1 8935
#define shiroiginshouslashSGBPal3c2 6596
#define shiroiginshouslashSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define shiroiginshouslashCGBPal0c0 6076
#define shiroiginshouslashCGBPal0c1 8935
#define shiroiginshouslashCGBPal0c2 6596
#define shiroiginshouslashCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define shiroiginshouslashCGBPal1c0 6076
#define shiroiginshouslashCGBPal1c1 8935
#define shiroiginshouslashCGBPal1c2 6596
#define shiroiginshouslashCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define shiroiginshouslashCGBPal2c0 6076
#define shiroiginshouslashCGBPal2c1 8935
#define shiroiginshouslashCGBPal2c2 6596
#define shiroiginshouslashCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define shiroiginshouslashCGBPal3c0 6076
#define shiroiginshouslashCGBPal3c1 8935
#define shiroiginshouslashCGBPal3c2 6596
#define shiroiginshouslashCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define shiroiginshouslashCGBPal4c0 6076
#define shiroiginshouslashCGBPal4c1 8935
#define shiroiginshouslashCGBPal4c2 6596
#define shiroiginshouslashCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define shiroiginshouslashCGBPal5c0 6076
#define shiroiginshouslashCGBPal5c1 8935
#define shiroiginshouslashCGBPal5c2 6596
#define shiroiginshouslashCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define shiroiginshouslashCGBPal6c0 6076
#define shiroiginshouslashCGBPal6c1 8935
#define shiroiginshouslashCGBPal6c2 6596
#define shiroiginshouslashCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define shiroiginshouslashCGBPal7c0 6076
#define shiroiginshouslashCGBPal7c1 8935
#define shiroiginshouslashCGBPal7c2 6596
#define shiroiginshouslashCGBPal7c3 5344

/* SGB palette entries. */
#define shiroiginshouslashSGB0 0
#define shiroiginshouslashSGB1 0
#define shiroiginshouslashSGB2 0
#define shiroiginshouslashSGB3 0
#define shiroiginshouslashSGB4 0
#define shiroiginshouslashSGB5 0
#define shiroiginshouslashSGB6 0
#define shiroiginshouslashSGB7 0
#define shiroiginshouslashSGB8 0
#define shiroiginshouslashSGB9 0
#define shiroiginshouslashSGB10 0
#define shiroiginshouslashSGB11 0
#define shiroiginshouslashSGB12 0
#define shiroiginshouslashSGB13 0
#define shiroiginshouslashSGB14 0
#define shiroiginshouslashSGB15 0
#define shiroiginshouslashSGB16 0
#define shiroiginshouslashSGB17 0
/* Start of tile array. */
extern const unsigned char shiroiginshouslash[];

#endif

/* End of SILVERSILVERSWORD.H */
