/*

 STARTTEXT.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 40

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __starttext_h_INCLUDE
#define __starttext_h_INCLUDE

/* Bank of tiles. */
#define texttilesBank 0

/* Super Gameboy palette 0 */
#define texttilesSGBPal0c0 21374
#define texttilesSGBPal0c1 16089
#define texttilesSGBPal0c2 10804
#define texttilesSGBPal0c3 234

/* Super Gameboy palette 1 */
#define texttilesSGBPal1c0 21374
#define texttilesSGBPal1c1 31705
#define texttilesSGBPal1c2 31540
#define texttilesSGBPal1c3 26255

/* Super Gameboy palette 2 */
#define texttilesSGBPal2c0 21374
#define texttilesSGBPal2c1 31
#define texttilesSGBPal2c2 21
#define texttilesSGBPal2c3 11

/* Super Gameboy palette 3 */
#define texttilesSGBPal3c0 21374
#define texttilesSGBPal3c1 8935
#define texttilesSGBPal3c2 6596
#define texttilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define texttilesCGBPal0c0 6076
#define texttilesCGBPal0c1 8935
#define texttilesCGBPal0c2 6596
#define texttilesCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define texttilesCGBPal1c0 6076
#define texttilesCGBPal1c1 8935
#define texttilesCGBPal1c2 6596
#define texttilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define texttilesCGBPal2c0 6076
#define texttilesCGBPal2c1 8935
#define texttilesCGBPal2c2 6596
#define texttilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define texttilesCGBPal3c0 6076
#define texttilesCGBPal3c1 8935
#define texttilesCGBPal3c2 6596
#define texttilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define texttilesCGBPal4c0 6076
#define texttilesCGBPal4c1 8935
#define texttilesCGBPal4c2 6596
#define texttilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define texttilesCGBPal5c0 6076
#define texttilesCGBPal5c1 8935
#define texttilesCGBPal5c2 6596
#define texttilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define texttilesCGBPal6c0 6076
#define texttilesCGBPal6c1 8935
#define texttilesCGBPal6c2 6596
#define texttilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define texttilesCGBPal7c0 6076
#define texttilesCGBPal7c1 8935
#define texttilesCGBPal7c2 6596
#define texttilesCGBPal7c3 5344

/* SGB palette entries. */
#define texttilesSGB0 0
#define texttilesSGB1 0
#define texttilesSGB2 0
#define texttilesSGB3 0
#define texttilesSGB4 0
#define texttilesSGB5 0
#define texttilesSGB6 0
#define texttilesSGB7 0
#define texttilesSGB8 0
#define texttilesSGB9 0
#define texttilesSGB10 0
#define texttilesSGB11 0
#define texttilesSGB12 0
#define texttilesSGB13 0
#define texttilesSGB14 0
#define texttilesSGB15 0
#define texttilesSGB16 0
#define texttilesSGB17 0
#define texttilesSGB18 0
#define texttilesSGB19 0
#define texttilesSGB20 0
#define texttilesSGB21 0
#define texttilesSGB22 0
#define texttilesSGB23 0
#define texttilesSGB24 0
#define texttilesSGB25 0
#define texttilesSGB26 0
#define texttilesSGB27 0
#define texttilesSGB28 0
#define texttilesSGB29 0
#define texttilesSGB30 0
#define texttilesSGB31 0
#define texttilesSGB32 0
#define texttilesSGB33 0
#define texttilesSGB34 0
#define texttilesSGB35 0
#define texttilesSGB36 0
#define texttilesSGB37 0
#define texttilesSGB38 0
#define texttilesSGB39 0
#define texttilesSGB40 0
/* Start of tile array. */
extern const unsigned char texttiles[];

#endif

/* End of STARTTEXT.H */
