/*

 TANUKI2.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 15

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __tanuki2_h_INCLUDE
#define __tanuki2_h_INCLUDE

/* Bank of tiles. */
#define tanukihappyBank 0

/* Super Gameboy palette 0 */
#define tanukihappySGBPal0c0 21374
#define tanukihappySGBPal0c1 16089
#define tanukihappySGBPal0c2 10804
#define tanukihappySGBPal0c3 234

/* Super Gameboy palette 1 */
#define tanukihappySGBPal1c0 21374
#define tanukihappySGBPal1c1 31705
#define tanukihappySGBPal1c2 31540
#define tanukihappySGBPal1c3 26255

/* Super Gameboy palette 2 */
#define tanukihappySGBPal2c0 21374
#define tanukihappySGBPal2c1 31
#define tanukihappySGBPal2c2 21
#define tanukihappySGBPal2c3 11

/* Super Gameboy palette 3 */
#define tanukihappySGBPal3c0 21374
#define tanukihappySGBPal3c1 8935
#define tanukihappySGBPal3c2 6596
#define tanukihappySGBPal3c3 5344

/* Gameboy Color palette 0 */
#define tanukihappyCGBPal0c0 6076
#define tanukihappyCGBPal0c1 8935
#define tanukihappyCGBPal0c2 6596
#define tanukihappyCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define tanukihappyCGBPal1c0 6076
#define tanukihappyCGBPal1c1 8935
#define tanukihappyCGBPal1c2 6596
#define tanukihappyCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define tanukihappyCGBPal2c0 6076
#define tanukihappyCGBPal2c1 8935
#define tanukihappyCGBPal2c2 6596
#define tanukihappyCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define tanukihappyCGBPal3c0 6076
#define tanukihappyCGBPal3c1 8935
#define tanukihappyCGBPal3c2 6596
#define tanukihappyCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define tanukihappyCGBPal4c0 6076
#define tanukihappyCGBPal4c1 8935
#define tanukihappyCGBPal4c2 6596
#define tanukihappyCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define tanukihappyCGBPal5c0 6076
#define tanukihappyCGBPal5c1 8935
#define tanukihappyCGBPal5c2 6596
#define tanukihappyCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define tanukihappyCGBPal6c0 6076
#define tanukihappyCGBPal6c1 8935
#define tanukihappyCGBPal6c2 6596
#define tanukihappyCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define tanukihappyCGBPal7c0 6076
#define tanukihappyCGBPal7c1 8935
#define tanukihappyCGBPal7c2 6596
#define tanukihappyCGBPal7c3 5344

/* SGB palette entries. */
#define tanukihappySGB0 0
#define tanukihappySGB1 0
#define tanukihappySGB2 0
#define tanukihappySGB3 0
#define tanukihappySGB4 0
#define tanukihappySGB5 0
#define tanukihappySGB6 0
#define tanukihappySGB7 0
#define tanukihappySGB8 0
#define tanukihappySGB9 0
#define tanukihappySGB10 0
#define tanukihappySGB11 0
#define tanukihappySGB12 0
#define tanukihappySGB13 0
#define tanukihappySGB14 0
#define tanukihappySGB15 0
/* Start of tile array. */
extern const unsigned char tanukihappy[];

#endif

/* End of TANUKI2.H */
