/*

 TANUKI6.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 15

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __tanuki6_h_INCLUDE
#define __tanuki6_h_INCLUDE

/* Bank of tiles. */
#define tanukiwin2Bank 0

/* Super Gameboy palette 0 */
#define tanukiwin2SGBPal0c0 21374
#define tanukiwin2SGBPal0c1 16089
#define tanukiwin2SGBPal0c2 10804
#define tanukiwin2SGBPal0c3 234

/* Super Gameboy palette 1 */
#define tanukiwin2SGBPal1c0 21374
#define tanukiwin2SGBPal1c1 31705
#define tanukiwin2SGBPal1c2 31540
#define tanukiwin2SGBPal1c3 26255

/* Super Gameboy palette 2 */
#define tanukiwin2SGBPal2c0 21374
#define tanukiwin2SGBPal2c1 31
#define tanukiwin2SGBPal2c2 21
#define tanukiwin2SGBPal2c3 11

/* Super Gameboy palette 3 */
#define tanukiwin2SGBPal3c0 21374
#define tanukiwin2SGBPal3c1 8935
#define tanukiwin2SGBPal3c2 6596
#define tanukiwin2SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define tanukiwin2CGBPal0c0 6076
#define tanukiwin2CGBPal0c1 8935
#define tanukiwin2CGBPal0c2 6596
#define tanukiwin2CGBPal0c3 5344

/* Gameboy Color palette 1 */
#define tanukiwin2CGBPal1c0 6076
#define tanukiwin2CGBPal1c1 8935
#define tanukiwin2CGBPal1c2 6596
#define tanukiwin2CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define tanukiwin2CGBPal2c0 6076
#define tanukiwin2CGBPal2c1 8935
#define tanukiwin2CGBPal2c2 6596
#define tanukiwin2CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define tanukiwin2CGBPal3c0 6076
#define tanukiwin2CGBPal3c1 8935
#define tanukiwin2CGBPal3c2 6596
#define tanukiwin2CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define tanukiwin2CGBPal4c0 6076
#define tanukiwin2CGBPal4c1 8935
#define tanukiwin2CGBPal4c2 6596
#define tanukiwin2CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define tanukiwin2CGBPal5c0 6076
#define tanukiwin2CGBPal5c1 8935
#define tanukiwin2CGBPal5c2 6596
#define tanukiwin2CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define tanukiwin2CGBPal6c0 6076
#define tanukiwin2CGBPal6c1 8935
#define tanukiwin2CGBPal6c2 6596
#define tanukiwin2CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define tanukiwin2CGBPal7c0 6076
#define tanukiwin2CGBPal7c1 8935
#define tanukiwin2CGBPal7c2 6596
#define tanukiwin2CGBPal7c3 5344

/* SGB palette entries. */
#define tanukiwin2SGB0 0
#define tanukiwin2SGB1 0
#define tanukiwin2SGB2 0
#define tanukiwin2SGB3 0
#define tanukiwin2SGB4 0
#define tanukiwin2SGB5 0
#define tanukiwin2SGB6 0
#define tanukiwin2SGB7 0
#define tanukiwin2SGB8 0
#define tanukiwin2SGB9 0
#define tanukiwin2SGB10 0
#define tanukiwin2SGB11 0
#define tanukiwin2SGB12 0
#define tanukiwin2SGB13 0
#define tanukiwin2SGB14 0
#define tanukiwin2SGB15 0
/* Start of tile array. */
extern const unsigned char tanukiwin2[];

#endif

/* End of TANUKI6.H */
