/*

 TANUKI5.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 15

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __tanuki5_h_INCLUDE
#define __tanuki5_h_INCLUDE

/* Bank of tiles. */
#define tanukiwin1Bank 0

/* Super Gameboy palette 0 */
#define tanukiwin1SGBPal0c0 21374
#define tanukiwin1SGBPal0c1 16089
#define tanukiwin1SGBPal0c2 10804
#define tanukiwin1SGBPal0c3 234

/* Super Gameboy palette 1 */
#define tanukiwin1SGBPal1c0 21374
#define tanukiwin1SGBPal1c1 31705
#define tanukiwin1SGBPal1c2 31540
#define tanukiwin1SGBPal1c3 26255

/* Super Gameboy palette 2 */
#define tanukiwin1SGBPal2c0 21374
#define tanukiwin1SGBPal2c1 31
#define tanukiwin1SGBPal2c2 21
#define tanukiwin1SGBPal2c3 11

/* Super Gameboy palette 3 */
#define tanukiwin1SGBPal3c0 21374
#define tanukiwin1SGBPal3c1 8935
#define tanukiwin1SGBPal3c2 6596
#define tanukiwin1SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define tanukiwin1CGBPal0c0 6076
#define tanukiwin1CGBPal0c1 8935
#define tanukiwin1CGBPal0c2 6596
#define tanukiwin1CGBPal0c3 5344

/* Gameboy Color palette 1 */
#define tanukiwin1CGBPal1c0 6076
#define tanukiwin1CGBPal1c1 8935
#define tanukiwin1CGBPal1c2 6596
#define tanukiwin1CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define tanukiwin1CGBPal2c0 6076
#define tanukiwin1CGBPal2c1 8935
#define tanukiwin1CGBPal2c2 6596
#define tanukiwin1CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define tanukiwin1CGBPal3c0 6076
#define tanukiwin1CGBPal3c1 8935
#define tanukiwin1CGBPal3c2 6596
#define tanukiwin1CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define tanukiwin1CGBPal4c0 6076
#define tanukiwin1CGBPal4c1 8935
#define tanukiwin1CGBPal4c2 6596
#define tanukiwin1CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define tanukiwin1CGBPal5c0 6076
#define tanukiwin1CGBPal5c1 8935
#define tanukiwin1CGBPal5c2 6596
#define tanukiwin1CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define tanukiwin1CGBPal6c0 6076
#define tanukiwin1CGBPal6c1 8935
#define tanukiwin1CGBPal6c2 6596
#define tanukiwin1CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define tanukiwin1CGBPal7c0 6076
#define tanukiwin1CGBPal7c1 8935
#define tanukiwin1CGBPal7c2 6596
#define tanukiwin1CGBPal7c3 5344

/* SGB palette entries. */
#define tanukiwin1SGB0 0
#define tanukiwin1SGB1 0
#define tanukiwin1SGB2 0
#define tanukiwin1SGB3 0
#define tanukiwin1SGB4 0
#define tanukiwin1SGB5 0
#define tanukiwin1SGB6 0
#define tanukiwin1SGB7 0
#define tanukiwin1SGB8 0
#define tanukiwin1SGB9 0
#define tanukiwin1SGB10 0
#define tanukiwin1SGB11 0
#define tanukiwin1SGB12 0
#define tanukiwin1SGB13 0
#define tanukiwin1SGB14 0
#define tanukiwin1SGB15 0
/* Start of tile array. */
extern const unsigned char tanukiwin1[];

#endif

/* End of TANUKI5.H */
