/*

 TANUKI1.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 15

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __tanuki1_h_INCLUDE
#define __tanuki1_h_INCLUDE

/* Bank of tiles. */
#define tanukiloseBank 0

/* Super Gameboy palette 0 */
#define tanukiloseSGBPal0c0 21374
#define tanukiloseSGBPal0c1 16089
#define tanukiloseSGBPal0c2 10804
#define tanukiloseSGBPal0c3 234

/* Super Gameboy palette 1 */
#define tanukiloseSGBPal1c0 21374
#define tanukiloseSGBPal1c1 31705
#define tanukiloseSGBPal1c2 31540
#define tanukiloseSGBPal1c3 26255

/* Super Gameboy palette 2 */
#define tanukiloseSGBPal2c0 21374
#define tanukiloseSGBPal2c1 31
#define tanukiloseSGBPal2c2 21
#define tanukiloseSGBPal2c3 11

/* Super Gameboy palette 3 */
#define tanukiloseSGBPal3c0 21374
#define tanukiloseSGBPal3c1 8935
#define tanukiloseSGBPal3c2 6596
#define tanukiloseSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define tanukiloseCGBPal0c0 6076
#define tanukiloseCGBPal0c1 8935
#define tanukiloseCGBPal0c2 6596
#define tanukiloseCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define tanukiloseCGBPal1c0 6076
#define tanukiloseCGBPal1c1 8935
#define tanukiloseCGBPal1c2 6596
#define tanukiloseCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define tanukiloseCGBPal2c0 6076
#define tanukiloseCGBPal2c1 8935
#define tanukiloseCGBPal2c2 6596
#define tanukiloseCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define tanukiloseCGBPal3c0 6076
#define tanukiloseCGBPal3c1 8935
#define tanukiloseCGBPal3c2 6596
#define tanukiloseCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define tanukiloseCGBPal4c0 6076
#define tanukiloseCGBPal4c1 8935
#define tanukiloseCGBPal4c2 6596
#define tanukiloseCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define tanukiloseCGBPal5c0 6076
#define tanukiloseCGBPal5c1 8935
#define tanukiloseCGBPal5c2 6596
#define tanukiloseCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define tanukiloseCGBPal6c0 6076
#define tanukiloseCGBPal6c1 8935
#define tanukiloseCGBPal6c2 6596
#define tanukiloseCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define tanukiloseCGBPal7c0 6076
#define tanukiloseCGBPal7c1 8935
#define tanukiloseCGBPal7c2 6596
#define tanukiloseCGBPal7c3 5344

/* SGB palette entries. */
#define tanukiloseSGB0 0
#define tanukiloseSGB1 0
#define tanukiloseSGB2 0
#define tanukiloseSGB3 0
#define tanukiloseSGB4 0
#define tanukiloseSGB5 0
#define tanukiloseSGB6 0
#define tanukiloseSGB7 0
#define tanukiloseSGB8 0
#define tanukiloseSGB9 0
#define tanukiloseSGB10 0
#define tanukiloseSGB11 0
#define tanukiloseSGB12 0
#define tanukiloseSGB13 0
#define tanukiloseSGB14 0
#define tanukiloseSGB15 0
/* Start of tile array. */
extern const unsigned char tanukilose[];

#endif

/* End of TANUKI1.H */
