/*

 TANUKI8.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 15

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __tanuki8_h_INCLUDE
#define __tanuki8_h_INCLUDE

/* Bank of tiles. */
#define tanukinormalBank 0

/* Super Gameboy palette 0 */
#define tanukinormalSGBPal0c0 21374
#define tanukinormalSGBPal0c1 16089
#define tanukinormalSGBPal0c2 10804
#define tanukinormalSGBPal0c3 234

/* Super Gameboy palette 1 */
#define tanukinormalSGBPal1c0 21374
#define tanukinormalSGBPal1c1 31705
#define tanukinormalSGBPal1c2 31540
#define tanukinormalSGBPal1c3 26255

/* Super Gameboy palette 2 */
#define tanukinormalSGBPal2c0 21374
#define tanukinormalSGBPal2c1 31
#define tanukinormalSGBPal2c2 21
#define tanukinormalSGBPal2c3 11

/* Super Gameboy palette 3 */
#define tanukinormalSGBPal3c0 21374
#define tanukinormalSGBPal3c1 8935
#define tanukinormalSGBPal3c2 6596
#define tanukinormalSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define tanukinormalCGBPal0c0 6076
#define tanukinormalCGBPal0c1 8935
#define tanukinormalCGBPal0c2 6596
#define tanukinormalCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define tanukinormalCGBPal1c0 6076
#define tanukinormalCGBPal1c1 8935
#define tanukinormalCGBPal1c2 6596
#define tanukinormalCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define tanukinormalCGBPal2c0 6076
#define tanukinormalCGBPal2c1 8935
#define tanukinormalCGBPal2c2 6596
#define tanukinormalCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define tanukinormalCGBPal3c0 6076
#define tanukinormalCGBPal3c1 8935
#define tanukinormalCGBPal3c2 6596
#define tanukinormalCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define tanukinormalCGBPal4c0 6076
#define tanukinormalCGBPal4c1 8935
#define tanukinormalCGBPal4c2 6596
#define tanukinormalCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define tanukinormalCGBPal5c0 6076
#define tanukinormalCGBPal5c1 8935
#define tanukinormalCGBPal5c2 6596
#define tanukinormalCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define tanukinormalCGBPal6c0 6076
#define tanukinormalCGBPal6c1 8935
#define tanukinormalCGBPal6c2 6596
#define tanukinormalCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define tanukinormalCGBPal7c0 6076
#define tanukinormalCGBPal7c1 8935
#define tanukinormalCGBPal7c2 6596
#define tanukinormalCGBPal7c3 5344

/* SGB palette entries. */
#define tanukinormalSGB0 0
#define tanukinormalSGB1 0
#define tanukinormalSGB2 0
#define tanukinormalSGB3 0
#define tanukinormalSGB4 0
#define tanukinormalSGB5 0
#define tanukinormalSGB6 0
#define tanukinormalSGB7 0
#define tanukinormalSGB8 0
#define tanukinormalSGB9 0
#define tanukinormalSGB10 0
#define tanukinormalSGB11 0
#define tanukinormalSGB12 0
#define tanukinormalSGB13 0
#define tanukinormalSGB14 0
#define tanukinormalSGB15 0
/* Start of tile array. */
extern const unsigned char tanukinormal[];

#endif

/* End of TANUKI8.H */
