/*

 TANUKI7.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 15

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __tanuki7_h_INCLUDE
#define __tanuki7_h_INCLUDE

/* Bank of tiles. */
#define tanukisadBank 0

/* Super Gameboy palette 0 */
#define tanukisadSGBPal0c0 21374
#define tanukisadSGBPal0c1 16089
#define tanukisadSGBPal0c2 10804
#define tanukisadSGBPal0c3 234

/* Super Gameboy palette 1 */
#define tanukisadSGBPal1c0 21374
#define tanukisadSGBPal1c1 31705
#define tanukisadSGBPal1c2 31540
#define tanukisadSGBPal1c3 26255

/* Super Gameboy palette 2 */
#define tanukisadSGBPal2c0 21374
#define tanukisadSGBPal2c1 31
#define tanukisadSGBPal2c2 21
#define tanukisadSGBPal2c3 11

/* Super Gameboy palette 3 */
#define tanukisadSGBPal3c0 21374
#define tanukisadSGBPal3c1 8935
#define tanukisadSGBPal3c2 6596
#define tanukisadSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define tanukisadCGBPal0c0 6076
#define tanukisadCGBPal0c1 8935
#define tanukisadCGBPal0c2 6596
#define tanukisadCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define tanukisadCGBPal1c0 6076
#define tanukisadCGBPal1c1 8935
#define tanukisadCGBPal1c2 6596
#define tanukisadCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define tanukisadCGBPal2c0 6076
#define tanukisadCGBPal2c1 8935
#define tanukisadCGBPal2c2 6596
#define tanukisadCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define tanukisadCGBPal3c0 6076
#define tanukisadCGBPal3c1 8935
#define tanukisadCGBPal3c2 6596
#define tanukisadCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define tanukisadCGBPal4c0 6076
#define tanukisadCGBPal4c1 8935
#define tanukisadCGBPal4c2 6596
#define tanukisadCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define tanukisadCGBPal5c0 6076
#define tanukisadCGBPal5c1 8935
#define tanukisadCGBPal5c2 6596
#define tanukisadCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define tanukisadCGBPal6c0 6076
#define tanukisadCGBPal6c1 8935
#define tanukisadCGBPal6c2 6596
#define tanukisadCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define tanukisadCGBPal7c0 6076
#define tanukisadCGBPal7c1 8935
#define tanukisadCGBPal7c2 6596
#define tanukisadCGBPal7c3 5344

/* SGB palette entries. */
#define tanukisadSGB0 0
#define tanukisadSGB1 0
#define tanukisadSGB2 0
#define tanukisadSGB3 0
#define tanukisadSGB4 0
#define tanukisadSGB5 0
#define tanukisadSGB6 0
#define tanukisadSGB7 0
#define tanukisadSGB8 0
#define tanukisadSGB9 0
#define tanukisadSGB10 0
#define tanukisadSGB11 0
#define tanukisadSGB12 0
#define tanukisadSGB13 0
#define tanukisadSGB14 0
#define tanukisadSGB15 0
/* Start of tile array. */
extern const unsigned char tanukisad[];

#endif

/* End of TANUKI7.H */
