/*

 TUTORIALTWO.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 4
   Map size      : 20 x 210
   Tile set      : Shogimenutiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __tutorialtwo_h_INCLUDE
#define __tutorialtwo_h_INCLUDE

#define pagetwoWidth 20
#define pagetwoHeight 210
#define pagetwoBank 4

#define pagetwo pagetwoPLN0
extern const unsigned char pagetwoPLN0[];

#endif

/* End of TUTORIALTWO.H */
