/*

 TUTORIALONE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 4
   Map size      : 20 x 202
   Tile set      : Shogimenutiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __tutorialone_h_INCLUDE
#define __tutorialone_h_INCLUDE

#define pageoneWidth 20
#define pageoneHeight 202
#define pageoneBank 4

#define pageone pageonePLN0
extern const unsigned char pageonePLN0[];

#endif

/* End of TUTORIALONE.H */
