/*

 WEAPONS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 5

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __weapons_h_INCLUDE
#define __weapons_h_INCLUDE

/* Bank of tiles. */
#define attacknumberBank 0

/* Super Gameboy palette 0 */
#define attacknumberSGBPal0c0 32767
#define attacknumberSGBPal0c1 18270
#define attacknumberSGBPal0c2 666
#define attacknumberSGBPal0c3 0

/* Super Gameboy palette 1 */
#define attacknumberSGBPal1c0 32767
#define attacknumberSGBPal1c1 25368
#define attacknumberSGBPal1c2 12684
#define attacknumberSGBPal1c3 0

/* Super Gameboy palette 2 */
#define attacknumberSGBPal2c0 32767
#define attacknumberSGBPal2c1 12
#define attacknumberSGBPal2c2 24
#define attacknumberSGBPal2c3 31

/* Super Gameboy palette 3 */
#define attacknumberSGBPal3c0 32767
#define attacknumberSGBPal3c1 8935
#define attacknumberSGBPal3c2 6596
#define attacknumberSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define attacknumberCGBPal0c0 6076
#define attacknumberCGBPal0c1 8935
#define attacknumberCGBPal0c2 6596
#define attacknumberCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define attacknumberCGBPal1c0 6076
#define attacknumberCGBPal1c1 8935
#define attacknumberCGBPal1c2 6596
#define attacknumberCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define attacknumberCGBPal2c0 6076
#define attacknumberCGBPal2c1 8935
#define attacknumberCGBPal2c2 6596
#define attacknumberCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define attacknumberCGBPal3c0 6076
#define attacknumberCGBPal3c1 8935
#define attacknumberCGBPal3c2 6596
#define attacknumberCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define attacknumberCGBPal4c0 6076
#define attacknumberCGBPal4c1 8935
#define attacknumberCGBPal4c2 6596
#define attacknumberCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define attacknumberCGBPal5c0 6076
#define attacknumberCGBPal5c1 8935
#define attacknumberCGBPal5c2 6596
#define attacknumberCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define attacknumberCGBPal6c0 6076
#define attacknumberCGBPal6c1 8935
#define attacknumberCGBPal6c2 6596
#define attacknumberCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define attacknumberCGBPal7c0 6076
#define attacknumberCGBPal7c1 8935
#define attacknumberCGBPal7c2 6596
#define attacknumberCGBPal7c3 5344

/* SGB palette entries. */
#define attacknumberSGB0 0
#define attacknumberSGB1 1
#define attacknumberSGB2 1
#define attacknumberSGB3 1
#define attacknumberSGB4 1
#define attacknumberSGB5 2
/* Start of tile array. */
extern const unsigned char attacknumber[];

#endif

/* End of WEAPONS.H */
